appsmithorg/appsmith-docs

quick-start.md
The steps mentioned in docker section shows step number as 1 for all steps mentioned in this section.
I have changed the number of the step to 1,2,3 and 4 .
Fixes appsmithorg/appsmith#904
=> [Docs]Fixed docker section steps number to correct numbers

SUMMARY.md
Fixes [#939](https://github.com/appsmithorg/appsmith/issues/939) by @Nikhil-Nandagopal 
This pr fixes the order of widgets in the widget reference section in SUMMARY.md and arranges them alphabetically.
=> Sort widgets alphabetically in widget-reference section

third-party-services/google-login.md
Added APPSMITH_OAUTH2_ALLOWED_DOMAINS parameter to the docker.env section of the Google OAuth login page. Fixes appsmithorg/appsmith#1148
=> Added APPSMITH_OAUTH2_ALLOWED_DOMAINS parameter to Google OAuth login page

core-concepts/apis/running-apis-on-page-load.md, core-concepts/connecting-to-databases/README.md, core-concepts/connecting-ui-and-logic/working-with-js-libraries.md, enabling-3p-services.md, function-reference/navigateto.md, quick-start.md, third-party-services/email/README.md, third-party-services/email/amazon-ses.md, third-party-services/email/sendgrid.md, third-party-services/github-login.md, third-party-services/google-login.md, third-party-services/google-maps.md
Changed cases for references of "Appsmith" in documentation pages. Also fixed typo in JS libraries documentation page.
Fixes appsmithorg/appsmith#1321
=> Changed cases for Appsmith and fixed typo

datasource-reference/querying-amazon-s3.md
1. Amazon s3 documentation page is not able to parse enumeration and images are not expanding on click. Adding space before enumerations and images to see if it helps.
=> fix formatting for amazon s3 doc - add space before enumeration and images.

troubleshooting-guide/deployment-errors.md
Edited the docs to point to an updated line number.
Also, Instead of linking to a line number, replaced it with a canonical URL.
Fixes #123
=> Fix outdated link in Ports Unavailable section

how-to-guides/how-to-upload-to-s3.md
- change s3 download steps by commenting out few lines to show use via JS edit mode only, as the download action using onSuccess property is broken currently. Fixing it going to take some time, hence hide the steps using onSuccess property so that users don't get confused. 
- The older steps have not been deleted but only commented out, since we would need them once the issue is fixed.
- For reference: https://github.com/appsmithorg/appsmith/issues/4262
=> Fix: fix s3 download steps

how-to-guides/backup-restore.md
Adding --drop argument to mongorestore to ensure that existing collections created when the server comes up for the first time are dropped and only then does a collection get restored. This is important for data sanity of the restored dump
Fixes : [https://github.com/appsmithorg/appsmith/issues/5643](https://github.com/appsmithorg/appsmith/issues/5643)
=> Updating mongorestore command to fix mongodump-mongorestore flow for migrating appsmith instance

setup/docker/README.md
This code block is rendered with a copy button in the UI, and this copy button is copying the comment in addition to the command, which makes it unfriendly for pasting.
=> fix: Remove comment line in code block for copying

widget-reference/list.md
This PR adds the info about the usage of `items` and `currentItem` to use the input widgets inside the list widget.
=> Add info about List widget v2

framework-reference/appsmith.md
These fields were historically already available, but weren't documented. This PR just documents them.
Related: https://github.com/appsmithorg/appsmith/issues/7294.
=> docs: Add more fields in appsmith.user object

core-concepts/connecting-to-data-sources/querying-a-database/README.md, core-concepts/displaying-data-read/README.md, troubleshooting-guide/application-errors.md
Using [JavaScript keywords](https://www.w3schools.com/js/js_reserved.asp) and [the window object methods and properties](https://www.w3schools.com/jsref/obj_window.asp) as entity names can lead to bugs on Appsmith. 
These names aren't valid as entity names.
=> docs: Add list of invalid names for queries and widgets

widget-reference/filepicker.md
Forgot the line break which displayed the markdown instead of the intended appearence.
=> docs: Fixed the properties list

how-to-guides/oauth2-authorization-for-google-sheets.md
1. "[...] and **in return**, receive a unique access token **in return**[sic]." - one of the "in return"-s is redundant
2. "Make sure the URL you’re requesting **it**[sic] from the data source." - should be "**is**"
3. "Next, you can use this response and render it **on to**[sic] a table widget on Appsmith" - "on to" and "onto" are **not** the same
=> docs: Fix grammar in oauth2-authorization-for-google-sheets.md

setup/kubernetes.md
Helm repo is located at `https://helm.appsmith.com`. This doc still uses the old URL, which will soon be removed.
=> fix: Fix Helm repo URL

security.md
`The Appsmith**'**s backend system doesn't s`
Notice `**'**`.
=> Remove improper markdown around apostrophe

setup/docker.md
I've added a note for the users to enable the auto-update for Appsmith, by uncommenting the commented lines in the docker-compose.yml.
=> Added note to enable watchtower for docker-compose

website/docs/getting-started/setup/instance-configuration/email/gmail.md, website/docs/reference/datasources/using-smtp.md
This PR adds a segue + link from the SMTP datasource docs -> the instructions for setting up a Gmail App Password, as well as a slight clarification on the latter page.
Also includes a pass of small tweaks to satisfy the linter. (The first two commits are the ones that affect this ticket, the third is the linter stuff).
Resolves [ticket #16844](https://github.com/appsmithorg/appsmith/issues/16844).
=> #16844 Connect Gmail app pwd docs to SMTP docs page

website/docs/getting-started/setup/installation-guides/aws-ecs.md
FIxed the broken links under Further Reading on [this](https://docs.appsmith.com/getting-started/setup/installation-guides/aws-ecs) page
=> Fix: Updating links in  aws-ecs installation docs

website/docs/reference/widgets/iframe.md
There's two changes in this.
1. The example code is wrapped in a backtick-string, inside double-braces, but doesn't use any interpolation. So, it's the same thing as directly writing the markup.
2. The code block and the following paragraph need to be part of the 2nd point. For this, they need to be lined up with `We need to embed...`. See the markup and layout in the screenshots to understand this. I can elaborate further on why this is important if needed. Let me know.
=> fix: Simplify messaging example and fix markup

website/docs/getting-started/setup/installation-guides/docker/README.md
The relative paths with long `../` chains are hard to grok and easy to get wrong. They also need fixing when a page is moved from one folder to another. They also need fixing when a page is converted to a section, like moving `document.md` to `document/README.md`. Docusaurus lets us use absolute paths from the `website/docs` folder, which is very convenient and the links are easy to read. They also don't need fixing when the page is moved to another section.
I'm not looking to change _all_ links in the docs to use this, but am using this PR to showcase this so that we can use absolute paths from here on please?
=> feat: Use absolute paths in links to internal pages

.github/styles/Vocab/technical/accept.txt, website/docs/reference/widgets/table/inline-editing.md
This PR adds changes to the `updatedRow` property of the table widget. 
Please refer to the issue: Issue: #618
=> docs: changed the documentation for updatedRow property of tablewidget

website/docusaurus.config.js
The link to edit pages reads "Edit this page", but clicking it actually _views_ the page, not edit it. This PR changes it to actually edit the page directly.
Also removed some comments that are not needed, and are a little misleading now.
=> fix: Fix edit link and remove misleading comments

website/docs/core-concepts/connecting-to-data-sources/README.md, website/docs/core-concepts/connecting-to-data-sources/authentication/README.md, website/docs/learning-and-resources/integrations.md, website/docusaurus.config.js
Fixed broken links for following:
- updated the correct link to point-> learning-and-resources/how-to-guides/aws-whitelist
- updated the tutorial link to point -> https://www.appsmith.com/blog?cat=Tutorial
- Removed link from the example - `https://mock-api.appsmith.com/`
=> chore: fix broken links

website/docs/reference/widgets/currency-input.md, website/docs/reference/widgets/datepicker.md, website/docs/reference/widgets/input.md, website/docs/reference/widgets/multi-tree-select.md, website/docs/reference/widgets/multiselect.md, website/docs/reference/widgets/phone-input.md, website/docs/reference/widgets/select.md, website/docs/reference/widgets/tree-select.md
Fixes - #668 
Within the following widgets there are new events
1. Input widgets - Input, currency, phone - They now support onFocus and onBlur functionality
2. Select widgets - Select, multiselect, multi-tree, tree - They now support onDropdownOpen and onDropdownClose functionality
3. Datepicker - It now supports onFocus and onBlur functionality
=> feat: 668 widget focus and blur events

website/docs/reference/appsmith-framework/widget-actions/intervals-time-events.md
Updated docs on [intervals-time-events](https://docs.appsmith.com/reference/appsmith-framework/widget-actions/intervals-time-events#settimeout) page under `setTimeout` heading.
Updated function signature, arguments, and example code snippet to use the correct syntax.
=> fix: Incorrect signature/args/snippet for setTimeout()

website/docs/reference/datasources/querying-redis.md
- Removed `"Please refer to the official [documentation](https://redis.io/commands) for the list of commands that are supported." `
- Lintr Fixes
=> fix: Redis does not support all commands

website/docs/advanced-concepts/version-control-with-git/README.md
Removal of `\` that was showing up in https://docs.appsmith.com/advanced-concepts/version-control-with-git
=> fix: Typo fix in the git readme

.gitbook/assets/docker-compose.yml
Updated the docker-compose.yml in the old gitbook assets since our marketplace builds still use this resource.
=> fix: update watchtower hook env and tag

website/static/img/docker-compose_(3).yml
Updated docker-compose.yml : Watcher now uses latest image tag
=> fix: use latest watchtower tag

.github/styles/Microsoft/Auto.yml, website/docs/getting-started/setup/installation-guides/docker/README.mdx
- Adding more Instructions to map backup/restore with Appsmith updates, so that searching for rollback points to appsmithctl backup/restore.
- Recommend users to backup before manual update
- Link to restore using a backup on auto-backup section
- Mentioned Watchtower requirements for auto-backup to be enabled.
=> docs: Mentioned Watchtower needs hooks enabled for auto-backup 

website/docs/advanced-concepts/access-control/granular-access-control/roles.md
The default role for all users provides powerful control over what a user can see and do in an instance. Admins can use it to provide really fine-grained base level access to their users.
=> fix: GAC | Added documentation for Default Role for All Users

website/docs/getting-started/setup/installation-guides/kubernetes/migrate-to-helm-chart-v2-ce.md
The backup tar must have timestamp it in, otherwise `backup` would not work.
=> fix: Update migrate-to-helm-chart-v2-ce backup file name

website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/active-directory.md, website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/auth0.md, website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/okta.md, website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/ping-identity.md
Adding a note for the lack of support of the HS256 algorithm in OIDC token signing.
I've added the note in each IDP page subtly because this is an edge case setup. I'm worried that users might get unnecessarily distracted if we show the note promptly or on the OIDC page.
=> fix: Notes for lack of HS256 support

website/docusaurus.config.js, website/package-lock.json, website/package.json
- Added segment analytics using `@twilio-labs/docusaurus-plugin-segment` plugin.
- Other analytics snippets like Google Analytics will be loaded in via segment. 
- Uses the same `writeKey` as `app.appsmith.com` and `www.appsmith.com` so that we can track user journeys.
- Manually tested and verified that the script executes as expected.
=> feat: added segment analytics

website/docs/advanced-concepts/version-control-with-git/working-with-branches.md
Note for errors caused by remote branch protections.
=> fix: Notes on git branch protections

.github/styles/Vocab/technical/accept.txt, website/docs/getting-started/setup/installation-guides/docker/README.mdx, website/docs/getting-started/setup/instance-management/README.mdx, website/docs/getting-started/setup/instance-management/update-appsmith.md, website/package-lock.json, website/package.json, website/sidebars.js
- Updates to Docker Installation Page
- Installation instructions for Docker Compose
- Added a new doc for Updating Appsmith
- The doc is added under Instance Management
- The doc instructs users to update Appsmith to the latest version
- Further reading removed - as users already have Appsmith instance up and running and configured as per their needs. This page only instructs them to update to the latest version.
- Restart containers section removed - as this is obsolete
=> fix: Rehaul docker installation guide

website/docs/getting-started/setup/installation-guides/docker/migrate.md
- Updated docker link in migrate docs
=> chore: updating outdated docker link

website/src/css/custom.css
fixes - #939
@danciaclara - As we have hidden the buttons, the users don't know where to navigate other than the sidebar for the pages where there is no **Further reading** section. IMO, we should mandate the **Further reading** section for every page. Thoughts?
=> fix: Added css to hide next and previous buttons

website/docusaurus.config.js, website/static/scripts/analyticsEvents.js
- New script to add an event listener on click events which will fire an `analytics.track()` event to segment.
- Most of the code is to find the `page_section` of the clicked element so that we can accurately track usage.
This data will be used to analyze user's journeys in the docs and help us improve the user experience.
=> feat: track clicks on all links with segment

website/docs/getting-started/setup/installation-guides/kubernetes/README.mdx, website/docs/getting-started/setup/installation-guides/kubernetes/migrate-k8s.md
- Change the link for `kubectl` install docs to point to the English version of the docs. Previously pointed to the Vietnamese docs.
=> fix: k8s tools `kubectl` docs link

website/src/components/YoutubeEmbed.js
- When user clicks the play icon for a youtube embed video, it loads in and autoplays. Previous behaviour required the user to click "play" twice.
- This maintains the facade `srcDoc` which loads the thumbnail fast, keeping load speeds quick while also bringing the ux closer to normal iframe embed.
Some formatting was auto-applied, sorry about that. Actual changes are only in line 18, 19 and 24.
=> feat: autoplay youtube embed when video is clicked

website/src/components/Message.js
- Use `className` instead of `class` for CSS in `<Message />` component because only `className` is valid JSX.
- This fixes the error shown in the console.
- We don't see any difference in the rendered component now because no css is currently passed through this.
=> fix: use `className` in `<Message />`

website/docs/getting-started/setup/instance-management/appsmithctl.mdx
Sync backup to S3 is only available for backup instance (backup) command
=> chore: moved sync backup under backup instance

website/docusaurus.config.js
Added a condition to the segment plugin to make sure the its only fired in the Vercel production environment.
Using the available system variable from Vercel - https://vercel.com/docs/concepts/projects/environment-variables/system-environment-variables
Addresses https://github.com/appsmithorg/appsmith-docs/issues/1187
=> fix: added production condition to segment script

website/docs/advanced-concepts/granular-access-control/README.md, website/docs/advanced-concepts/granular-access-control/roles.md, website/docs/advanced-concepts/invite-users.md
**Invite Users**
- Changed built-in roles to default roles
- Make applications public is now H2
- updated business edition callout
**GAC** 
- updated business edition callout
**Roles**
- Changed the heading from default roles to instance roles
- Updated information for Default roles for all users
- Made the permission categories explanation simpler
=> fix: GAC and invite users

website/docs/core-concepts/data-access-and-binding/querying-a-database/query-settings.md
Added a line indicating the maximum timeout duration for a query. (6000 ms)
[Discussion on Slack](https://theappsmith.slack.com/archives/CNQ9Q91C0/p1682671783898449)
=> docs: query timeout max duration

website/docs/reference/datasources/querying-elasticsearch.md
Incorporates review feedback:
* Added labels for **Path** and **Body** fields for clarity
* Removed "Create Multiple" subheading
* Updated "Update" heading snippet to be more flexible
I have:
=> fix: Elasticsearch rehaul review

website/docs/reference/datasources/querying-oracle.md
Review feedback:
* Removes quotations from snippets in Oracle docs
I have:
=> fix: Update Oracle docs snippets

website/docs/reference/widgets/chart.mdx
Review comments:
"The type, datasource, and chart attribute bit are confusing. Keep it simple
The custom chart needs 2 properties
Type
Datasource
2. Go to the [fusion chart docs](https://www.fusioncharts.com/dev/chart-attributes/area2d) and copy the type from the javascript alias on top and the datasource from the code at the bottom (use an image to highlight these 2 on the page) and paste it in the custom chart field.
3. Each type has a different configuration for chart and data. You can refer the fusion chart docs for the configuration options"
I have:
=> fix: custom chart

website/vercel.json
The old location of the "Connect to Local Datasource" how-to guide results in a 404. PR adds a redirect rule to its proper location.
I have:
=> fix: added redirect rule for Connect to Local Datasource

website/docs/reference/widgets/audio-recorder.md, website/docs/reference/widgets/checkbox-group.md, website/docs/reference/widgets/datepicker.md, website/docs/reference/widgets/divider.md, website/docs/reference/widgets/filepicker.md, website/docs/reference/widgets/icon-button.md, website/docs/reference/widgets/iframe.md, website/docs/reference/widgets/image.md, website/docs/reference/widgets/list.md, website/docs/reference/widgets/maps.md, website/docs/reference/widgets/menu-button.md, website/docs/reference/widgets/modal.md, website/docs/reference/widgets/multi-tree-select.md, website/docs/reference/widgets/multiselect.md, website/docs/reference/widgets/rating.md, website/docs/reference/widgets/rich-text-editor.md, website/docs/reference/widgets/stat-box.md, website/docs/reference/widgets/switch.md, website/docs/reference/widgets/tabs.md, website/docs/reference/widgets/tree-select.md, website/docs/reference/widgets/video.md
=> fix: removing old widget videos

website/docs/reference/appsmith-framework/context-object.md
Remove the backslash between Geolocation_API url that is giving a 404 page not found.
I have:
=> fix: Update context object

website/docs/getting-started/setup/instance-configuration/README.mdx, website/docs/getting-started/setup/instance-configuration/authentication/github-login.md, website/docs/getting-started/setup/instance-configuration/authentication/google-login.md, website/docs/getting-started/setup/instance-configuration/custom-domain/README.md, website/docs/getting-started/setup/instance-configuration/custom-mongodb-redis.md, website/docs/getting-started/setup/instance-configuration/email/README.md
=> fix: add callout to mention env variable takes precedence over Admin settings

website/vercel.json
=> Fix: old tutorial redirects

website/docs/core-concepts/data-access-and-binding/querying-a-database.md
Adds a little subheading that describes how to continue seeing App errors while in view mode.
I have:
=> fix: Added mention of Debug mode

website/sidebars.js, website/vercel.json
- Updated the name of the **Advanced Concepts** and **Learning and Resources** section (Have not changed slugs)
- Removed the **More** category
- Rearranged the order of pages in Advanced Concepts
- Temporarily hiding the Keyboard shortcuts page (will be added in another section where we have content for UI)
I have:
=> fix: change group names

.github/styles/Vocab/technical/accept.txt, website/docs/connect-data/reference/query-settings.md
Rehaul of Query Settings page in Reference section of Connect Data.
Resolves #1428 
* rm video, link instead "to see how to use smart json substitution, see..."
* separate settings with "query/API"
* link for "UTF equivalents"
* "Available for API queries" into sentence form
* prepared statements: available for SQL databases
* prepared statements: fix unclear "toggles using"
* prep statements: "For more details, see ..."
* prep state: move "available on" to penultimate sentence
* check for timeout error link
* don't mention "avail for all query types"
* "setting to be >turned off<"
* rm disabled from accepted terms
* fix "enabled" also
* smart json/bson substitution: more detail on why it's useful
* mention when a setting is on by default
I have:
=> fix: Query Settings Rehaul

.github/styles/Vocab/technical/accept.txt, website/docs/connect-data/concepts/how-to-use-prepared-statements.md
Rehaul of Prepared Statements concept page in Connect Data section.
* intro: use "explain" not "describe"
* lowercase "Prepared Statements"
* intro: how they're used -> why they're used
* Benefits and Limitations headings, rm "Prepared Statements"
* What are prepared statements heading -> "Overview"
* rm link to prepared statements wikipedia. add link elsewhere if a doc contains more info, else omit
* Check whether DBMS should be referred to as RDBMS -- _(found that DBMS should suffice)_
* Table1.searchText sentence reshuffling
* {?} change to ?
* lifecycle -> workflow
* remove "ing" from the lifecycle verbs
* "preparing" part: "The query" not "Your query"
* DB server -> database server
* don't link to widgets
* rm "extreme"
* widget names in code not bold
* Added line to highlight …
=> fix: Prepared Statements Rehaul

website/docs/getting-started/setup/instance-configuration/authentication/github-login.md, website/docs/getting-started/setup/instance-configuration/authentication/google-login.md, website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/active-directory.md, website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/auth0.md, website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/aws-cognito.md, website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/okta.md, website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/ping-identity.md, website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/active-directory.mdx, website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/auth0.mdx, website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/okta.mdx, website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/ping-identity.mdx, website/docs/getting-started/setup/instance-configuration/custom-domain/README.md, website/docs/getting-started/setup/instance-configuration/custom-domain/configure-tls.mdx, website/docs/getting-started/setup/instance-configuration/custom-mongodb-redis.md, website/docs/getting-started/setup/instance-configuration/disable-intercom.md, website/docs/getting-started/setup/instance-configuration/google-maps.mdx, website/docs/getting-started/setup/instance-management/README.mdx, website/docs/getting-started/setup/instance-management/appsmithctl.mdx, website/docs/getting-started/setup/instance-management/maintenance-window.md, website/docs/getting-started/setup/instance-management/supervisor.md
- Added self-hosted instance to either prerequisites or to the document introduction.
I have:
=> chore: add self-hosted instance reference for configurations

website/docs/connect-data/reference/querying-amazon-s3.md, website/sidebars.js
Updates S3 datasource docs page to adhere to new Diataxis format.
Resolves #1510
- fix: create multiple files: content: expects array of file objects
- fix: delete multiple files: list of paths: file paths, not filenames
I have:
=> fix: Update S3 docs to Diataxis

website/docs/connect-data/reference/graphql.md
Updates GraphQL datasource docs to new Diataxis format.
Resolves #1547 
I have:
=> fix: Update GraphQL to Diataxis

website/docs/reference/widgets/iframe.md
=> fix: Limitations for custom widgets

website/docs/connect-data/reference/authenticated-api.md, website/docs/connect-data/reference/graphql.md
Update from review of GraphQL diataxis format
* Removed datasource configuration fields from GraphQL page, instead just links to identical Authenticated API datasource page.
I have:
=> fix: GraphQL review update

website/docs/connect-data/reference/airtable.md, website/docs/connect-data/reference/authenticated-api.md, website/docs/connect-data/reference/curl-import.md, website/docs/connect-data/reference/graphql.md, website/docs/connect-data/reference/hubspot.md, website/docs/connect-data/reference/querying-amazon-s3.md, website/docs/connect-data/reference/querying-arango-db.md, website/docs/connect-data/reference/querying-dynamodb.md, website/docs/connect-data/reference/querying-elasticsearch.md, website/docs/connect-data/reference/querying-firestore.md, website/docs/connect-data/reference/querying-google-sheets.md, website/docs/connect-data/reference/querying-mongodb/README.md, website/docs/connect-data/reference/querying-oracle.md, website/docs/connect-data/reference/querying-postgres.md, website/docs/connect-data/reference/querying-redis.md, website/docs/connect-data/reference/querying-redshift.md, website/docs/connect-data/reference/querying-snowflake-db.md, website/docs/connect-data/reference/rest-api.md, website/docs/connect-data/reference/twilio.md, website/docs/connect-data/reference/using-smtp.md
Added Troubleshooting section to the bottom of all datasource reference pages.
Resolves #1524 
I have:
=> fix: Added datasource troubleshooting headings

website/docs/product/security.md
Updates to Product Security page
Resolves #1492 
* Changed heading names from "Secure" to "safe"
* changed "tip" callout to "info"
* converted javascript security suggestion bullets into statement sentences.
* slight adjustments to sandboxed iframe area
I have:
=> fix: Update Security docs

website/docs/connect-data/reference/airtable.md, website/docs/connect-data/reference/authenticated-api.md, website/docs/connect-data/reference/hubspot.md, website/docs/connect-data/reference/query-settings.md, website/docs/connect-data/reference/querying-amazon-s3.md, website/docs/connect-data/reference/querying-arango-db.md, website/docs/connect-data/reference/querying-dynamodb.md, website/docs/connect-data/reference/querying-elasticsearch.md, website/docs/connect-data/reference/querying-firestore.md, website/docs/connect-data/reference/querying-google-sheets.md, website/docs/connect-data/reference/querying-mongodb/README.md, website/docs/connect-data/reference/querying-mssql.md, website/docs/connect-data/reference/querying-mysql.md, website/docs/connect-data/reference/querying-oracle.md, website/docs/connect-data/reference/querying-postgres.md, website/docs/connect-data/reference/querying-redis.md, website/docs/connect-data/reference/querying-redshift.md, website/docs/connect-data/reference/querying-snowflake-db.md, website/docs/connect-data/reference/rest-api.md, website/docs/connect-data/reference/twilio.md, website/docs/connect-data/reference/using-smtp.md
Changes properties entries in datasource pages from <b> tags into h4 so that they are linkable.
Resolves #1620 
I have:
=> fix: Change datasource properties to headings

.github/styles/Google/Will.yml, website/docs/advanced-concepts/invite-users.md
This set of changes needs to be shipped after [this PR](https://github.com/appsmithorg/appsmith-ee/pull/2055) is merged into production, and tagged.
Fixes #1617 
I have:
=> docs: Changes to default roles as per access based on envs

website/docs/reference/widgets/README.md
=> fix: Widget landing page categorisation

website/docusaurus.config.js
=> fix: remove footer

website/sidebars.js
- Moved sample apps to Refernce under Build Apps section
- Removed link to templates
I have:
=> fix: Move Sample Apps to Build Apps

website/docs/build-apps/how-to-guides/README.md, website/docs/build-apps/reference/README.md, website/docs/connect-data/concepts/README.md, website/docs/connect-data/how-to-guides/README.md, website/docs/write-code/how-to-guides/README.md, website/docs/write-code/reference/README.md
- Changed the title to a link under the Build Apps and Write Code sections.
- Removed the View link at the bottom of the card
- Added cards in the sections under Connect Datasource in the landing page.
I have:
=> fix: Update landing page links 1708

website/docs/getting-started/setup/installation-guides/ansible.md, website/docs/getting-started/setup/installation-guides/google-cloud-run.mdx, website/sidebars.js, website/vercel.json
* Updated doc structure 
* Rewritten the instructions
* Removed CloudJiffy and Restack from sidebar
* Added redirect rules for CloudJiffy and Restack
Fixes #1743 
I have:
=> fix: Rehaul ansible installation guide

website/docs/getting-started/setup/installation-guides/docker/README.mdx
=> fix: Use http scheme in the community installation guide using docker

website/docs/connect-data/how-to-guides/README.md, website/docs/connect-data/how-to-guides/download-files-from-s3.md
=> fix: Added card for S3 file download on landing page

website/docs/connect-data/reference/querying-redis.md
Added a callout to specify that Appsmith does not support Redis connection using TLS.
closes #1667 
I have:
=> fix: Added callout for Redis connection using TLS

website/docs/connect-data/reference/querying-mongodb/README.md
=> fix: MongoDB Connection String URI format

website/docs/build-apps/reference/README.md, website/sidebars.js, website/vercel.json
=> fix: Remove Canvas Size page

website/docs/connect-data/reference/querying-google-sheets.md
=> fix: Gsheet Update code

website/docs/advanced-concepts/invite-users.md, website/docs/advanced-concepts/version-control-with-git/environments-with-git.md, website/docs/write-code/reference/Built-in-JS-Libraries.md, website/src/css/custom.css
=> fix: link hash tags overlap

website/docs/write-code/reference/Built-in-JS-Libraries.md
=> fix: Removed fast xml parser from the default libraries

website/docs/reference/appsmith-framework/widget-actions/navigate-to.md
=> fix: Added details for triple braces to query parameters

website/docs/build-apps/how-to-guides/insert-data.md, website/docs/build-apps/how-to-guides/submit-form-data.md, website/sidebars.js
=> fix: Insert data guide

website/docs/connect-data/how-to-guides/how-to-pass-params-to-an-api.mdx
=> fix: remove outdated video from Pass Runtime Parameters to Queries

website/docs/build-apps/how-to-guides/README.md
=> fix: Bind Data to Widgets typo

website/docs/build-apps/how-to-guides/browse-and-display-documents.md, website/sidebars.js
=> fix: Browse and Display Documents

website/docs/build-apps/how-to-guides/navigate-between-pages.md, website/sidebars.js
=> fix: Navigate between pages

website/docs/connect-data/how-to-guides/how-to-pass-params-to-an-api.mdx
Linking from the docs root (`/<path>`), as seems to be the convention.
=> fix: unbreak link

website/docs/getting-started/tutorials/the-basics/connect-query-display-data.md, website/docs/getting-started/tutorials/the-basics/write-js-code.md
Fixed some typos in the tutorial
I have:
=> fix: typos in tutorial

website/docs/reference/appsmith-framework/context-object.md
=> fix: Additional user attributes

.github/styles/config/vocabularies/technical/accept.txt, website/docs/getting-started/setup/installation-guides/kubernetes/README.mdx, website/docs/getting-started/setup/installation-guides/kubernetes/setup-kubernetes-cluster-aws-eks.md, website/sidebars.js
- A separate guide for setting up a Kubernetes cluster on AWS-EKS
- Updates to the installation guide to remove the setup instructions above and create relevant cross-references
* 
- 
=> fix: Updates to create a new guide for the AWS EKS Kubernetes Cluster

website/docs/getting-started/setup/instance-management/appsmithctl.mdx
Adds details about encrypted backups that include the salt/password in it.
Preview page at https://appsmith-docs-git-feat-encrypted-backups-get-appsmith.vercel.app/getting-started/setup/instance-management/appsmithctl.
* https://github.com/appsmithorg/appsmith/pull/29902
- 
=> feat: Changes about encrypted backups

website/docs/reference/appsmith-framework/widget-actions/close-modal.md, website/docs/reference/appsmith-framework/widget-actions/show-modal.md, website/docs/reference/widgets/modal.md
- Adds a references property for the Modal widget
- Describes how to use the above property in `showModal` & `closeModal` functions
* 
- 
=> feat: added modal name property references, showModal & closeModal usage

website/docs/getting-started/setup/installation-guides/docker/README.mdx
This top-level field has been obsoleted.
Ref: <https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-obsolete>.
[Slack thread](https://theappsmith.slack.com/archives/C02MUD8DNUR/p1715156294594419).
* 
- 
=> chore: Remove version in docker-compose.yml

website/docs/getting-started/setup/installation-guides/aws-ami.md, website/docs/getting-started/setup/installation-guides/aws-ecs-on-fargate.md, website/docs/getting-started/setup/installation-guides/aws-ecs/aws-ecs-on-ec2.md, website/docs/getting-started/setup/installation-guides/azure-aci.md, website/docs/getting-started/setup/installation-guides/digitalocean.md, website/docs/getting-started/setup/installation-guides/docker/README.mdx, website/docs/getting-started/setup/installation-guides/google-cloud-run.mdx, website/docs/getting-started/setup/installation-guides/kubernetes/README.mdx
- Added post-installation configurations for installation guides except Ansible.
* 
- 
=> fix: add post installation configurations for installation guides

website/docs/getting-started/setup/instance-configuration/http-proxy.md
Updated doc - [Configure HTTP/HTTPS proxy](https://appsmith-docs-git-fix-setup-proxy-for-appsmith-get-appsmith.vercel.app/getting-started/setup/instance-configuration/http-proxy)
- Added a Verify Connectivity section to verify if proxy configuration is required
- Rewrote the instructions, and updated section headings for clarity
- Rewrote the troubleshooting guide section
* 
- #2206
=> fix: Configure HTTP/HTTPs Proxy

website/docs/write-code/reference/Built-in-JS-Libraries.md
-  Removed the Fast XML Parser from built-in libraries as this is no longer supported
* 
- NA
=> chore: removed fast xml parser from built-in libraries section

website/docs/getting-started/setup/installation-guides/aws-ami.md, website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/entra-id.mdx, website/src/css/custom.css
- Updated docs to add video tutorial links 
- SAML SSO for Azure Entra 
- Install Appsmith using an Amazon AMI
- Added a CSS to show that the links are external.
- #2473
- #2474 
- 
=> fix: Add video tutorials for AMI and Entra ID

website/docs/reference/widgets/custom.md
=> fix: Custom onThemeChange fix

website/docs/reference/widgets/select.md
=> fix: Label Key Select

website/docs/reference/widgets/button/README.md, website/docs/reference/widgets/category-slider.md, website/docs/reference/widgets/code-scanner.md, website/docs/reference/widgets/filepicker.md, website/docs/reference/widgets/icon-button.md, website/docs/reference/widgets/json-form.md, website/docs/reference/widgets/menu/README.md, website/docs/reference/widgets/number-slider.md, website/docs/reference/widgets/range-slider.md
- The current references to the button color property in the docs suggest that users can change the font color of a button, which is not currently supported. However, there's an active [feature request](https://github.com/appsmithorg/appsmith/issues/15065) for this styling capability.
* 
- 
=> fix: button color property description

website/docs/getting-started/setup/environment-variables.md, website/docs/getting-started/setup/instance-configuration/file-size-limit.md, website/docs/help-and-support/troubleshooting-guide/action-errors/README.md
- Default file size limit was increased to 200 MB. GH issue for reference https://github.com/appsmithorg/appsmith/issues/14248
* 
- 
=> fix: default file size

website/docs/getting-started/setup/instance-management/update-appsmith.mdx
I'm updating the Kubernetes upgrade steps to explicitly set the version that should be used.
The old method assumed that the administrator was installing Appsmith in a non-HA installation and they actually may or may not actually trigger an upgrade in the default situation: it depends upon whether the new pod gets scheduled on a new node or not. It could even trigger a downgrade if the pod got scheduled on a node that happened to have an older copy of the Appsmith image.
I'm going to open a separate ticket to revamp the installation instructions for Kubernetes as using `latest` can lead to some unexpected situations depending upon how the cluster is setup.
* 
- 
From the below …
=> fix: update Kubernetes upgrade instructions to explicitly set image tag
