appsmithorg/appsmith-docs

CODE_OF_CONDUCT.md
CONTRIBUTING.md
core-concepts/connecting-ui-and-logic/working-with-JS-libraries.md

- Add contributing guidelines
- Update libraries examples with moment

Respository and Docs update

---

widget-reference/video.md

Fixes: #814 Create documentation for video widget

Fixes: #814 Create documentation for video widget

---

third-party-services/google-maps.md

Corrected the numbering where, 2 bullet points had the same numbering

#905: Updated google-maps.md to correct the numbering

---

function-reference/navigateto.md

Adds the target argument documentation

Add target argument in the navigateTo function

---

SUMMARY.md
datasource-reference/querying-amazon-s3.md

remove coming soon tag from summary page as well.
fix hint syntax

Remove coming soon from S3 documentation

---

datasource-reference/querying-mongodb/README.md

add steps to connect via SRV URL for mongo plugin.

add steps to connect via SRV URL for mongo plugin.

---

troubleshooting-guide/README.md
troubleshooting-guide/hint-messages.md

- add documentation for hint messages.
- arrange debug topics alphabetically.

add documentation for hint messages

---

widget-reference/filepicker.md
widget-reference/filepicker/README.md

- Update file widget, removed uploadFileUrls

fix: remove uploadFileUrls from property reference

---

core-concepts/connecting-to-data-sources/README.md

Include a missing part of the IP address character as shown [here](https://docs.appsmith.com/core-concepts/connecting-to-data-sources/connecting-to-databases)

Update README.md to display correct IPs to whitelist

---

SUMMARY.md
widget-reference/iframe.md

https://docs.appsmith.com/widget-reference/iframe
- Add the corresponding documentation for iframe widget

Iframe Widget Documentation

---

troubleshooting-guide/action-errors/postgres-plugin-errors.md

Fixes https://github.com/appsmithorg/appsmith/issues/3654

Added troubleshooting guide to data type errors in Prepared Statement in Postgres

---

widget-reference/image.md

https://docs.appsmith.com/widget-reference/image
we add a new feature rotation in the image widget so the document needs to update

update image widget doc

---

SUMMARY.md
core-concepts/connecting-to-data-sources/connecting-to-databases/README.md
datasource-reference/querying-arango-db.md

- documentation for ArangoDB plugin.
- some other minor fixes.

Feature: arangodb plugin documentation

---

framework-reference/resetwidget.md

Update default value fo resetWidget second argument

docs: Update resetWidget function docs

---

widget-reference/statbox.md

This PR adds new document for statsWidgets

add statbox widget document

---

SUMMARY.md
widget-reference/audio.md

Adds docs for [PR-7179](https://github.com/appsmithorg/appsmith/pull/7179)

feat: Add docs for Audio widget

---

widget-reference/table.md

-- Add the documentation for total records count property in table widget

feat: Total records count property in table widget

---

troubleshooting-guide/action-errors/README.md

All the links have been combined into this page: https://docs.appsmith.com/core-concepts/connecting-to-data-sources/querying-a-database

docs: Updated all the links to nonexistant pages

---

tutorials/building-a-store-catalog-manager/README.md
tutorials/building-a-store-catalog-manager/part-2-using-forms.md

Updated all the links I could find that linked to a nonexistent page about JS libraries supported.

docs: Updated JS libraries links

---

core-concepts/application-layout.md

1. "less than minimum" replaced with "less than the minimum"
2. "point of time" replaced with "point in time"

docs: Fix grammar in application-layout.md

---

framework-reference/appsmith.md

docs: geolocation api 

---

.github/github-actions-demo.yml
.vale.ini

**What:**
Appsmith documentation linter
**Problem Solved:**
The linter acts as an automated style guide for documentation. The purpose of this linter is to standardize grammar and word usage. This linter enforces the [Microsoft technical style guide](https://docs.microsoft.com/en-us/style-guide/welcome/). 
**How to Use:**
When a contributor pushes changes to the main branch the [github action is triggered and the linter checks markdown formatting and grammar](https://github.com/errata-ai/vale-action). 
**Additional Information:**
https://docs.errata.ai/vale/about
https://github.com/btford/write-good
https://docs.microsoft.com/en-us/style-guide/welcome/
@Pranay105

Documentation Linter

---

troubleshooting-guide/deployment-errors.md

Adding troubleshooting steps for v1.6.4 to documentation as well

chore: Adding troubleshooting steps to documentation as well

---

widget-reference/button-group.md

Adds button group YouTube video

chore: Adds button group video

---

getting-started/setting-up/heroku.md

Embeds Heroku setup video from YT

Embeds Heroku video from YT

---

widget-reference/chart.md

Adds custom chart YouTube video

chore: Adds custom chart video

---

widget-reference/chart.md

Added `Animate Loading` property definition in the docs of the chart widget

chore: update chart widget doc

---

framework-reference/navigateto.md

Fixes appsmithorg/appsmith#9564

Fix navigateTo description

---

how-to-guides/how-to-implement-custom-authentication-on-appsmith.md

Adds documentation and video guide for Google login with Xano

video: How To Setup Custom Google Login With Xano

---

how-to-guides/how-to-implement-custom-authentication-on-appsmith.md

Reverts appsmithorg/appsmith-docs#324

Revert "video: How To Setup Custom Google Login With Xano"

---

how-to-guides/how-to-implement-custom-authentication-on-appsmith.md

Adds documentation and video guide for "How To Setup Custom Google Login With Xano"
Video link https://www.youtube.com/watch?v=n3XSAA7q--I

feat: Adds video "How To Setup Custom Google Login With Xano"

---

widget-reference/switch-group.md

Adds documentation and video guide for "How To Use The Switch Group Widget"
Video link https://www.youtube.com/watch?v=p--j-QyBlAY

feat: Adds video "How To Use The Switch Group Widget"

---

widget-reference/table.md

Adds documentation and video guide for "How To Use The Table Widget"
Video link https://www.youtube.com/watch?v=-rzePEV2QQ8

feat: Adds video "How To Use The Table Widget"

---

core-concepts/writing-code/ext-libraries.md

Adds documentation and video guide for "How To Use The Built-In Libraries In Appsmith"
Video link https://www.youtube.com/watch?v=tqJna718tj4

feat: Adds video "How To Use The Built-In Libraries In Appsmith"

---

core-concepts/connecting-to-data-sources/querying-a-database/connect-to-apis.md

Adds documentation and video guide for "How To Pass Parameters To An API call"
Video link https://www.youtube.com/watch?v=znaaDiQbAS8

feat: Adds video "How To Pass Parameters To An API call"

---

widget-reference/tabs.md

Adds documentation and video guide for "How To Configure Tab Navigation"
Video link https://www.youtube.com/watch?v=dHeS5kPHlHE

feat: Adds video "How To Configure Tab Navigation"

---

setup/aws-ami.md

Docs incorrectly state HTTP when it should say SSH

fix: Update aws-ami.md

---

core-concepts/dynamic-ui/README.md

Adds documentation and video guide for "How To Dynamically Update Widget Properties"
Video link https://www.youtube.com/watch?v=vlx8TEuep5I

feat: Adds video "How To Dynamically Update Widget Properties"

---

core-concepts/writing-code/javascript-promises.md

Adds documentation and video guide for "How To Use JS Promises and Async/Await"
Video link https://www.youtube.com/watch?v=VuBycqPJVug

feat: Adds video "How To Use JS Promises and Async/Await"

---

setup/docker.md

Adds documentation and video guide for "How to Self-Host Appsmith with Docker"
Video link https://www.youtube.com/watch?v=Tde7GqE6FQQ

feat: Adds video "How to Self-Host Appsmith with Docker"

---

widget-reference/dropdown-1.md

Adds documentation and video guide for "How To Use The Select Widget"
Video link https://www.youtube.com/watch?v=zNw1yMwg-aY

feat: Adds video "How To Use The Select Widget"

---

setup/instance-configuration/custom-mongodb-redis.md

Added credentials to APPSMITH_MONGODB_URI sample

fix: Added credentials to APPSMITH_MONGODB_URI sample

---

how-to-guides/embed-appsmith-into-existing-application.md

Users have to add a meta tag in the head to ensure that the embedded application behaves properly.
https://github.com/appsmithorg/appsmith/issues/11363

fix: 11363 non responsiveness of embedded apps in iframe

---

widget-reference/text.md

Adds documentation and video guide for "How To Use The Text Widget"
Video link https://www.youtube.com/watch?v=-anmDHXDScQ

feat: Adds video "How To Use The Text Widget"

---

core-concepts/designing-an-application/README.md

Adds documentation and video guide for "How To Use The New Drag & Drop Experience"
Video link https://www.youtube.com/watch?v=NB8Btt0aw0g

feat: Adds video "How To Use The New Drag & Drop Experience"

---

widget-reference/table.md

Adds documentation and video guide for "How To Setup Server-Side Search For The Table Widget"
Video link https://www.youtube.com/watch?v=3ayioaw5uj8

feat: Adds video "How To Setup Server-Side Search For The Table Widget"

---

datasource-reference/using-smtp.md

Adds documentation and video guide for "How To Send Emails With The SMTP Integration"
Video link https://www.youtube.com/watch?v=hAln7o1aUA4

feat: Adds video "How To Send Emails With The SMTP Integration"

---

troubleshooting-guide/README.md

Adds documentation and video guide for "How To Find & Fix Bugs With The Linter and Debugger"
Video link https://www.youtube.com/watch?v=DuDBMCqG2Zo

feat: Adds video "How To Find & Fix Bugs With The Linter and Debugger"

---

troubleshooting-guide/widget-errors.md

Adds documentation and video guide for "How To Debug With Console.log()"
Video link https://www.youtube.com/watch?v=YLnvb9_k96s

feat: Adds video "How To Debug With Console.log()"

---

README.md

I've made the recommended changes with slight modifications to help them read better.
#311

feat: Update title and phrase in the introduction.

---

core-concepts/connecting-to-data-sources/authentication/README.md

Adds documentation and video guide for "How To Use Smart JSON Substitution"
Video link https://www.youtube.com/watch?v=-Z3y-pdNhXc

feat: Adds video "How To Use Smart JSON Substitution"

---

.gitbook/assets/docker-compose (1).yml

Removed watchtower from docker-compose (1).yml

Fix: Removed watchtower from docker compose

---

widget-reference/container.md

Adds documentation and video guide for "How To Use The Container Widget"
Video link https://www.youtube.com/watch?v=mfPGTUxr6SY

feat: Adds video "How To Use The Container Widget"

---

datasource-reference/querying-postgres.md

Adds documentation and video guide for "How To Use Prepared Statements To Prevent SQL Injections"
Video link https://www.youtube.com/watch?v=Q69wdQEQbbE

feat: Adds video "How To Use Prepared Statements To Prevent SQL Injections"

---

widget-reference/currency-input.md

Adds documentation and video guide for "How To Use The Currency Input Widget"
Video link https://www.youtube.com/watch?v=I-FusTdnJeE

feat: Adds video "How To Use The Currency Input Widget"

---

widget-reference/form.md

Adds documentation and video guide for "How To Use The Form Widget"
Video link https://www.youtube.com/watch?v=UgpQ0ZOnzdg

feat: Adds video "How To Use The Form Widget"

---

widget-reference/document-viewer.md

Adds documentation and video guide for "How To Generate PDF Reports With Apitemplate.io"
Video link https://www.youtube.com/watch?v=8j6Z9bZvLqA

feat: Adds video "How To Generate PDF Reports With Apitemplate.io"

---

widget-reference/phone-input.md

Adds documentation and video guide for "How To Use The Phone Input Widget"
Video link https://www.youtube.com/watch?v=DuyMuOZm83g

feat: Adds video "How To Use The Phone Input Widget"

---

widget-reference/json-form.md

Adds documentation and video guide for "How To Use The JSON Form Widget"
Video link https://www.youtube.com/watch?v=Zk6df9mOtQA

feat: Adds video "How To Use The JSON Form Widget"

---

widget-reference/list.md

Adds documentation and video guide for "How To Use The List Widget"
Video link https://www.youtube.com/watch?v=QyIO51Wzao8

feat: Adds video "How To Use The List Widget"

---

.github/ISSUE_TEMPLATE/--documentation-improvement.yaml

Added a documentation improvement template.

Added a doc improvement issue template

---

.github/drafts/16296/16296_self-hosting_outline.md

16296 - Self hosting

---

.github/drafts/16296/16296_self-hosting.md

The initial draft is based on the outline approved and available [here](https://github.com/appsmithorg/appsmith-docs/blob/v1.4/.github/drafts/16296/16296_self-hosting_outline.md). Some pointers:
* The quotes will be added to GitBook as hints
* The links are created as placeholders, and the contents will be replaced on GitBook with the appropriate cross-reference of page/section

#16296 - Self-hosting - Initial Draft

---

.github/drafts/16521/16521-Code-Scanner-Outline.md

16521- code scanner widget - outline

---

.github/drafts/15681/15681_Writing_Code_Reactive_Draft.md

Content amends "Reactive" section of docs page Core Concepts > Writing Code, found [here](https://docs.appsmith.com/core-concepts/writing-code#reactive).
Commit reflects requested changes from previous review.
Original ticket found [here](https://github.com/appsmithorg/appsmith/issues/15681).

15681: Updated Draft (Writing Code | Reactive)

---

website/src/css/custom.css

added padding for grid container layout

added padding

---

.github/drafts/15938/15938_Audit_Logs_Outline.md

Outline for the new Audit Logs feature. Any additional sections that should be added?
~~There is a note on Ln.11 about the names of the events; a table of these names can be found [here on notion](https://www.notion.so/appsmith/Events-List-bcaba08d34f94b90a655d835de6788b7).~~
~~Original first engineering draft can be found [here](https://docs.google.com/document/d/1ZhdZZMY0Rw5sdkLe4giQLI7eAMelf_3oIMYaUL6LwmU/edit)~~ (Correct first draft can be found in this appsmith-docs repo on branch `v1.4` at ~/.github/drafts/15938/[auditLog-first-draft.md](https://github.com/appsmithorg/appsmith-docs/blob/v1.4/.github/drafts/15938/auditLog-first-draft.md))

15938: Outline (Audit Logs)

---

website/docs/learning-and-resources/integrations.md
website/src/css/custom.css

Updated Integrations Layout

---

website/docs/learning-and-resources/integrations.md
website/docs/learning-and-resources/sample-apps.md
website/src/css/custom.css

Sample Apps Updated Layout

---

website/src/css/custom.css

Updated the layout, sidebar , styles on the docs

UI update on docs

---

website/docs/reference/widgets/table/column-settings.md

Mirroring the changes made in PR 492 from the v1.4 branch

Mirror v1.4 PR#492 (Table Widget > Column > Image Size)

---

website/src/css/custom.css

Updated Custom.css

---

.github/drafts/16858/#16858_RBAC_outline.md

Added outline for the RBAC documentation.
We have picked up three use cases that will explain the power of RBAC in Appsmith.

16858- Adding RBAC outline

---

website/docusaurus.config.js
website/static/scripts/intercomSettings.js

Intercom messenger integration

added intercom

---

website/src/css/custom.css

imageCSS fix

---

website/config.json

fix: Fix domain in sitemap configuration

---

website/docusaurus.config.js

Added sitemap configuration as per https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap.

feat: Add sitemap plugin and configuration

---

website/config.json
website/docusaurus.config.js

Fix sitemap url

---

website/vercel.json

Added redirect rules for older versions of docs maintained on GitBook

fix: Add redirects for all URLs from old sitemap.xml

---

website/docs/core-concepts/connecting-to-data-sources/authentication/README.md

fixing hint in API doc

---

website/docs/reference/widgets/rating.md

Added the Read-Only property with a description to the Properties table for the Rating widget. Resolves #496

Rating Widget: Add Read-Only

---

website/docs/advanced-concepts/version-control-with-git/README.md

- Updating info section on the Git landing page

fix: Updating info section on Git homepage

---

.github/ISSUE_TEMPLATE/--documentation-improvement.yaml

Removed the search terms field and why the change is needed question.

fix: Updated issue template for doc improvement

---

website/src/components/YoutubeEmbed.js

to centre align the captions and have font style as italic.

fix: added video caption styles

---

website/docs/learning-and-resources/tutorials/building-a-store-catalog-manager/creating-interactive-views.md
website/docs/learning-and-resources/tutorials/building-a-store-catalog-manager/using-forms.md

- Updated the selectedRow property to triggeredRow as the value of the row is captured as part of triggeredRow when an action is triggered from a button click.
- Updated using forms to add an instruction for setting up label property.
- Fixed some linter issues too. The rest of the issues can be taken care of when we rehaul the tutorial.

fix: 560-selectedRow-table-action

---

.gitignore
website/docs/reference/widgets/table/README.md

- Added total records count in the table widget.
- Updated .gitignore with vale.ini file

feat: Adding total records count

---

website/docs/reference/widgets/table/README.md

- Addressing comments by @jnikhila from the previous PR as that was merged

fix: fixes for total record count

---

website/docs/advanced-concepts/audit-logs.md
website/docs/advanced-concepts/version-control-with-git/README.md
website/docs/advanced-concepts/version-control-with-git/connecting-to-git-repository.md
website/docs/getting-started/setup/instance-configuration/authentication/json-web-tokens-jwt.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/README.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/active-directory.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/auth0.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/okta.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/ping-identity.md
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/README.md
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/active-directory.md
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/auth0.md
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/okta.md
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/ping-identity.md

- Added pricing link to Business Edition
- Changed Enterprise Edition to Business Edition

chore: Added link to pricing

---

website/vercel.json

fix: Updated- writing code rule

---

.github/styles/README.md

To quickly configure and use linter in VS Code Editor.

chore: Added README.md

---

website/docs/getting-started/setup/instance-configuration/custom-mongodb-redis.md

Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1669518643771859?thread_ts=1669404108.528309&cid=C0341RERY4R

docs: Added note on required roles for MongoDB

---

.github/styles/Microsoft/HeadingAcronyms.yml
.gitignore
website/docs/learning-and-resources/sample-apps.md
website/src/css/custom.css

Had to also make linter changes to the Sample apps file as that is the only page where we use tabs. And the tab item headings were all in uppercase, changed that and some linter related things

chore: New style for tabs

---

website/docs/getting-started/setup/installation-guides/docker/README.mdx

Updating bitly links in the docker intsallation guide

fix: updating docker-compose links

---

website/docs/core-concepts/building-ui/dynamic-ui/README.md
website/docs/reference/widgets/README.md

- Fixed the headings on the widgets landing page
- Updates Setting widget height section under Building a dynamic UI

fix: minor fixes around auto height

---

website/docs/reference/widgets/currency-input.md
website/docs/reference/widgets/datepicker.md
website/docs/reference/widgets/input.md
website/docs/reference/widgets/multi-tree-select.md
website/docs/reference/widgets/multiselect.md
website/docs/reference/widgets/phone-input.md
website/docs/reference/widgets/select.md
website/docs/reference/widgets/tree-select.md

This reverts commit b8548dd6416d2d9811781a08487ee884420a5ee6.

chore: Revert "feat: 668 widget focus and blur events (#669)"

---

website/docs/advanced-concepts/more/how-to-work-with-local-apis-on-appsmith.md

chore: fixed broken link

---

website/docs/getting-started/setup/instance-management/appsmithctl.md

How To Use Appsmithctl For Instance Management

chore: add video

---

website/docs/reference/widgets/currency-input.md
website/docs/reference/widgets/datepicker.md
website/docs/reference/widgets/input.md
website/docs/reference/widgets/multi-tree-select.md
website/docs/reference/widgets/multiselect.md
website/docs/reference/widgets/phone-input.md
website/docs/reference/widgets/select.md
website/docs/reference/widgets/tree-select.md

Raised a new PR to add changes related to #668 - onFocus and onBlur events.

fix: 668 widget focus blur

---

.github/ISSUE_TEMPLATE/--add-documentation-request.yaml
.github/ISSUE_TEMPLATE/--documentation-improvement.yaml

Added release version and date

chore: Updated issue templates

---

website/src/components/Message.js
website/src/css/custom.css
website/src/theme/MDXComponents.js

- Message component
- CSS for error message

feat: Added Message Component

---

website/sidebars.js

Updated Mongo to MongoDB to reflect the same in sidebar

chore: fixed sidebar

---

website/docs/getting-started/setup/instance-configuration/custom-mongodb-redis.md

- To add a disclaimer to [Custom MongoDB & Redis Documentation](https://docs.appsmith.com/getting-started/setup/instance-configuration/custom-mongodb-redis).

chore: Added a disclaimer

---

.github/styles/Vocab/technical/accept.txt
website/docs/reference/datasources/querying-postgres.md

-  Updated postgres official documentation link
- Lintr fixes

fix: Postgres documentation link 

---

website/docs/help-and-support/troubleshooting-guide/js-errors.md

- added info for 2 error(string and number)
- fixed the error message layout 
- lintr fixes

fix: Troubleshooting - JS errors

---

website/docs/getting-started/start-building.md

fix: ensure quotation marks are not included in bold text

---

website/docs/getting-started/setup/installation-guides/heroku.md

For existing Appsmith Image. Changes migrated from PR #433

chore: fix instructions

---

website/docs/advanced-concepts/audit-logs.md

This now includes execution parameters and the size limit.

fix: Updated the Query Executed Log description

---

website/docs/reference/widgets/table/inline-editing.md

Adds description of all the new properties included for date cell editing in table widget.
Fixes #750

feat: Support date column editing in table widget

---

website/docs/help-and-support/troubleshooting-guide/application-errors.md
website/docs/help-and-support/troubleshooting-guide/deployment-errors.mdx
website/docs/help-and-support/troubleshooting-guide/js-errors.md

Changed doesn't to does not - to enable an error message search on Algolia.

chore: fixed contraction

---

website/docs/reference/datasources/graphql.md

Add Graphql tutorial video https://youtu.be/KPLrbp-4Y6E

feat: Adds Graphql video

---

website/docs/getting-started/setup/installation-guides/docker/README.mdx
website/docs/getting-started/setup/installation-guides/docker/install-business-edition.mdx

- Updated links in the main docker guide
- Added bitly link in the short version

chore: Updating bitly links for docker-compose

---

website/src/components/HideElements.js

Hide the intercom link on shorter version for customer billing.

fix: hide intercom on shorter version for customer billing

---

website/src/components/HideElements.js

As the intercom has a timeout set

fix: Added timeout

---

website/src/components/HideElements.js
website/src/css/custom.css

fixes https://github.com/appsmithorg/appsmith-docs/issues/818

fix: usage & billing installation docs step & intercom

---

website/src/components/HideElements.js

Fixes https://github.com/appsmithorg/appsmith-docs/issues/818

fix: Hide intercom launcher on select pages

---

website/docs/reference/widgets/code-scanner.md

Adds documentation and video guide for "How To Build A Self-Checkout Payment System With The CodeScanner Widget"
Video link https://www.youtube.com/watch?v=Suhefwa5pz0

feat: Adds video "How To Build A Self-Checkout Payment System With The CodeScanner Widget"

---

website/docs/reference/appsmith-framework/widget-actions/store-value.md

- updated structure and added clearStore() and removeValue()

[Rehaul]: Store value

---

.github/styles/Vocab/technical/accept.txt
website/docs/reference/widgets/button/README.md
website/vercel.json

This PR rehauls the Button Widget reference page.
[Notion doc](https://www.notion.so/appsmith/c27a515d06c54ec6b917c23bb0dc5d33?v=78e76316a1da430a93c072be04f441b4&p=f1104933a44f41edb372d048e86dc6ee&pm=s)
[Github Issue](https://github.com/appsmithorg/appsmith/issues/20019)
Resolves appsmithorg/appsmith#20019

fix: Button Rehaul

---

website/docs/reference/appsmith-framework/widget-actions/store-value.md

- deployment failed in the previous PR

fix: redeploying store value changes

---

website/docs/getting-started/setup/instance-configuration/authentication/json-web-tokens-jwt.md

Devs copy from here and it just looks wrong.

fix: Removed space in the access token copy

---

website/docs/advanced-concepts/version-control-with-git/connecting-to-git-repository.md

AWS code commit is not supported as one of the source control repositories, we're making that clear on the docs.

fix: Added info for the lack of support for AWS Code Commit

---

website/docs/getting-started/setup/README.md
website/docs/reference/widgets/list.md

chore: remove spacing in code blocks and grammar fixes

chore: minor fixes in list and self-hosting

---

website/docs/reference/widgets/table/README.md

Addresses comments based upon previous rehaul of Table widget

Fix: Table Rehaul review

---

website/docs/advanced-concepts/version-control-with-git/merging-branches.md

Added best practices for multi-developer teams to follow

fix: Added best practices to branch merging

---

.github/styles/Vocab/technical/accept.txt
website/docs/reference/widgets/form.md

Rehaul of [Form docs page](https://docs.appsmith.com/reference/widgets/form).
[Notion page](https://www.notion.so/appsmith/c27a515d06c54ec6b917c23bb0dc5d33?v=78e76316a1da430a93c072be04f441b4&p=021340590b1f4640b599f8228d08bb7f&pm=s)
Resolves [ticket](https://github.com/appsmithorg/appsmith-docs/issues/915)

fix: Form widget rehaul

---

website/docs/reference/widgets/form.md

Implements changes to Form widget rehaul after review with @danciaclara

fix: Form rehaul review fixes

---

.github/styles/Google/Headings.yml
website/docs/getting-started/setup/installation-guides/kubernetes/migrate-to-be-chart.md
website/docs/getting-started/setup/installation-guides/kubernetes/migrate-to-helm-chart-v2-ce.md
website/docs/getting-started/setup/upgrade-to-business-edition/docker.mdx
website/docs/getting-started/setup/upgrade-to-business-edition/kubernetes.md
website/docs/getting-started/setup/upgrade-to-business-edition/upgrade-docker-to-business-edition.mdx

Update BE to Business Edition and CE to Community Edition.

chore: fix the acronyms BE and CE

---

.github/styles/Vocab/technical/accept.txt
website/docs/reference/datasources/querying-google-sheets.md

Added a missing curly brace in a JSON Snippet, and did a linter fix pass on [google sheets docs](https://docs.appsmith.com/reference/datasources/querying-google-sheets)

fix: Added missing brace and linter fixes on Google Sheets

---

website/docs/advanced-concepts/embed-appsmith-into-existing-application.md

I tested this functionality with the below setup and it's working

fix: Added note for Google OAuth 2.0 config support for private embedded apps

---

website/docs/core-concepts/data-access-and-binding/displaying-data-read/README.md
website/docs/core-concepts/writing-code/README.md
website/docs/core-concepts/writing-code/workflows.md

- Updated structure
- Added examples
- Added "display data from sync/async JS functions"
- Grammar fixes.

Rehaul: displaying data

---

website/docs/reference/widgets/list.md

Two New properties added to List widget
1. Default Selected Item
2. Total Records
Also, `SelectedItemIndex` has been deprecated.

docs: update List widget properties

---

website/docs/advanced-concepts/audit-logs.md

Added retention policy in info.
I edited the video width to 100% so it can take up the column width as 750px was overlapping with the right sidebar on my screen. I'm a noob at HTML so, please revert if it looks wrong.

fix: Added audit log retention policy in docs

---

website/docs/advanced-concepts/version-control-with-git/commit-and-push.md

Someone asked this question on A-Force, updating here for future developers.

fix: Added note to include the tagging of commit author on Git

---

website/docs/getting-started/setup/instance-configuration/authentication/google-login.md

- Updated the content as per the feedback

fix:Google oauth

---

website/docs/reference/widgets/input.md

Removed unnecessary word in **Further reading**

fix: Input widget; removed extra word

---

website/docs/core-concepts/writing-code/javascript-editor-beta/README.md

Adds documentation and video guide for "How To Debug JavaScript With Console.log"
Video link https://www.youtube.com/watch?v=EYNPm9cJWGw

feat: Adds video "How To Debug JavaScript With Console.log"

---

website/docs/getting-started/setup/instance-configuration/authentication/github-login.md
website/docs/getting-started/setup/instance-configuration/authentication/google-login.md

- Added H3 headings under Configure Appsmith instance

fix: update headings for Google and GitHub OAuth

---

website/docs/advanced-concepts/version-control-with-git/working-with-branches.md

This same message is shown above, sorry, missed it yesterday.

fix: removed repeating content

---

website/docs/getting-started/setup/instance-configuration/custom-domain/README.md

- Change the callout style
- remove the sentence about secure connections in the introduction
- Remove the bullet style and keep it as a paragraph only.
- Remove too many links from the Troubleshooting section

fix: final review fixes

---

website/docs/reference/datasources/querying-mssql.md

Implements review feedback for [MS SQL docs](https://docs.appsmith.com/reference/datasources/querying-mssql).
Resolves [ticket](https://github.com/appsmithorg/appsmith-docs/issues/994)

fix: MS SQL rehaul review

---

website/docs/advanced-concepts/version-control-with-git/README.md

Added a note that HTTPS is not supported explicitly as we're getting A-Force questions on the same.

fix: Added note for non-support of HTTPS connections in Git

---

website/docs/reference/widgets/sliders/README.md

Adds documentation and video guide for "How To Use The Slider Widget"
Video link https://www.youtube.com/watch?v=3aszcdK1z0Y

feat: Adds video "How To Use The Slider Widget"

---

website/docs/getting-started/setup/installation-guides/aws-ecs-on-fargate.md

chore: broken internal links

---

website/docs/core-concepts/data-access-and-binding/querying-a-database/README.md

- Added a link to transform data section under Run a query section

chore: Mention transform data under run a query

---

website/docs/getting-started/setup/instance-configuration/custom-mongodb-redis.md

This is required for Git Import to work in scenarios of external MongoDB configurations
https://theappsmith.slack.com/archives/C0341RERY4R/p1678810579003419

fix: Added readPreference requirements for Git Import

---

website/docs/reference/datasources/querying-firestore.md

Adds documentation and video guide for "How To Import CSV Files Into Firebase"
Video link https://www.youtube.com/watch?v=9-BYpO3hj-4

feat: Adds video "How To Import CSV Files Into Firebase"

---

website/docusaurus.config.js
website/plugins/scarfplugin/index.js

Added Scarf tracking as a plugin.

fix: browser console error for scarf.

---

.github/styles/Google/Title.yml
.github/styles/Vocab/technical/accept.txt
website/docs/getting-started/setup/installation-guides/docker/migrate.md

fix: broken docker link

---

website/docs/advanced-concepts/audit-logs.md

GAC Audit Log events were missing from the documentation. Added them.

fix: Audit log event updates

---

.github/styles/Vocab/technical/accept.txt
website/docs/getting-started/faq.md
website/docs/getting-started/start-building.md
website/src/css/custom.css

- Fixed FAQ page
- Change font sizes for headings

fix: FAQ rehaul

---

website/config.json

fix: the search url issue for unwanted anchor getting appended

---

website/docs/getting-started/setup/instance-configuration/disable-intercom.md

Fix an issue with the intercom docs

fix: disable intercom docs

---

website/docs/getting-started/setup/instance-management/maintenance-window.md

fix: Rehaul Maintenance Window

---

website/docs/core-concepts/connecting-to-data-sources/authentication/connect-to-apis.md

- Fix for [#13411](https://github.com/appsmithorg/appsmith/issues/13411)
- Grammar fixes

fix: add info about reading response headers

---

website/docs/getting-started/setup/installation-guides/kubernetes/configure-high-availability.mdx
website/docs/getting-started/setup/instance-management/appsmithctl.mdx
website/docs/getting-started/setup/instance-management/update-appsmith.mdx

* Removed the Editions tab from the Kubernetes section
* Added steps to get the pod name

fix: Updates to appsmithctl Kubernetes section

---

website/docusaurus.config.js
website/plugins/scarfplugin/index.js
website/static/scripts/smartlook.js

Added env variable for production

fix: to trigger analysis only for prod in scarf and smartlook

---

website/docs/reference/datasources/querying-amazon-s3.md

Fixes a few small grammatical errors.

fix: Amazon S3 datasource grammar

---

website/docs/getting-started/setup/installation-guides/kubernetes/configure-high-availability.mdx
website/docs/getting-started/setup/installation-guides/kubernetes/publish-appsmith-online.mdx
website/docs/getting-started/setup/instance-configuration/README.mdx
website/docs/getting-started/setup/instance-management/appsmithctl.mdx

* Added section under Backup Instance for 
* Schedule backups for docker installation
* Updated the instructions for 
* Sync backup to s3 bucket and added steps to update Kubernetes using the `values.yaml` file

feat: add schedule backup to appsmithctl

---

.github/pull_request_template.md
.github/styles/Vocab/technical/accept.txt

Added a template that will add a checklist whenever a PR is created. The checklist will be used by the tech writers to manually verify and update the status.

chore: added a template to PR creation.

---

website/docs/reference/datasources/querying-mongodb/README.md
website/docs/reference/datasources/querying-postgres.md

fix: PostgreSQL and MongoDB fixes

---

website/docs/getting-started/setup/installation-guides/aws-ecs.md

I have:
Changes available as part of this PR:
* Formatting issue with bullets
* Updated the troubleshooting info to use the chat window.
* Added a script to verify if the window opens up.

fix: AWS ECS formatting changes

---

website/docs/reference/widgets/audio-recorder.md

fix: Audio Recorder Rehaul

---

.github/styles/Vocab/technical/accept.txt
website/docs/reference/widgets/audio.md

fix: Audio Rehaul

---

website/docs/reference/widgets/maps.md

There were three review comments:
1). Merge multi-marker section into the same **Add markers** section -> (done)
2). Get the Live location of end-users -> (for this, I connected with Dilip, and he said https://docs.appsmith.com/reference/widgets/maps#live-location, this code will get the end-users' location)
3). Remove the marker after tagging, -> so if we use `{{Map1.center}}` , it will remove the old marker when the new one is tagged. This is already in the search and tag section
I have:

fix: Map review fixes

---

1
website/docs/getting-started/setup/installation-guides/aws-ecs.md
website/docs/getting-started/setup/installation-guides/kubernetes/README.mdx
website/docs/getting-started/setup/installation-guides/kubernetes/configure-high-availability.mdx

I have:
Below are the changes for this PR:
- moved prerequisites under each tab
- removed Minikube from Business Edition tab
- removed Minikube from Configure High Availability tab

fix: updates to installation instructions for Kubernetes

---

website/docs/reference/widgets/audio-recorder.md

Fixes:
- Updated the S3 code
- Added a step about bucket name and file type.
I have:

fix: Audio Recorder Review Fixes

---

website/docs/reference/appsmith-framework/widget-actions/post-message.md

chore: Updating domain argument in Cross origin communication

---

website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/ping-identity.md

chore: Table header fix in Ping ID OIDC SSO

---

website/docs/reference/widgets/camera.md

- Updated the code block
I have:

fix: Camera review feedback

---

website/docs/getting-started/setup/instance-management/update-appsmith.mdx

fix: updated title and added a callout

---

website/docs/getting-started/setup/installation-guides/kubernetes/README.mdx
website/docs/getting-started/setup/upgrade-to-business-edition/docker.mdx
website/docs/getting-started/setup/upgrade-to-business-edition/kubernetes.md

fix: upgrade to business edition k8s

---

.github/styles/Google/Headings.yml
website/docs/reference/widgets/document-viewer.md

* Restructured and rewritten the doc
* Renamed the images/videos
-----
I have:

fix: Document Viewer

---

website/docs/getting-started/setup/installation-guides/aws-ami.md

feat: Updates to AWS AMI docs to add Business Edition instructions

---

website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/README.md

chore: minor fix in OIDC callout

---

.github/styles/Vocab/technical/accept.txt
website/docs/reference/widgets/rich-text-editor.md

fix: Rich Text Editor Rehaul

---

website/docs/getting-started/setup/instance-management/appsmithctl.mdx

chore: fixed commands for Kubernetes

---

website/docs/reference/widgets/rich-text-editor.md

fix: RTE minor update 

---

.github/styles/Vocab/technical/accept.txt
website/docs/reference/widgets/phone-input.md

fix: Phone Input Rehaul

---

website/docs/reference/widgets/currency-input.md

fix: Currency Input Review Fixes

---

website/docs/reference/widgets/phone-input.md

fix: Phone Input Review Fixes

---

website/docusaurus.config.js

fix: Removing links from top bar

---

website/docs/reference/widgets/table/README.md

fix: Table review fix

---

website/docs/reference/widgets/menu/README.md

fix: Menu review fix

---

website/src/css/custom.css

fix: Update search button width

---

website/docs/advanced-concepts/more/README.md
website/docs/learning-and-resources/how-to-guides/how-to-work-with-local-apis-on-appsmith.mdx

Updates to content and discoverability of **Connect to Local Datasource** how-to guide.
- Adds directions to direct user to the correct steps for their situation
- Removes old link from **Advanced Concepts > More**
Resolves #1360 
* ngrok at top level with all methods
* make ngrok the recommended way
* simplify explanation of ngrok
* call out the 2 methods that *do not work with cloud*
* edit pass to simplify steps where possible
* Tab names: "ngrok, localhost, docker datasource"
I have:

fix:Updates to Connect to Local Datasource

---

website/docs/getting-started/setup/installation-guides/kubernetes/README.mdx

feat: Adds kubernetes video

---

website/src/css/custom.css

fix: search box responsive

---

website/docs/reference/widgets/switch-group.md

fix: Switch Group Rehaul

---

website/docs/getting-started/setup/instance-configuration/email/README.md

chore: fixed cross-reference.

---

website/docs/reference/widgets/progress.md

fix: Progress Rehaul

---

website/docs/core-concepts/writing-code/javascript-editor-beta/README.md

Adds documentation and video guide for "How To Use The JS Editor In Appsmith"
Video link https://www.youtube.com/watch?v=_reF92On2tw

feat: Adds video "How To Use The JS Editor In Appsmith"

---

website/docusaurus.config.js

chore:remove the documentation link

---

website/vercel.json

chore:fix redirect rules

---

.github/styles/Vocab/technical/accept.txt
website/docs/reference/appsmith-framework/query-object.mdx

fix: updating Query object

---

website/docs/reference/widgets/multi-tree-select.md

fix: Minor fix Multi TreeSelect

---

website/docs/reference/appsmith-framework/query-object.mdx

chore: Query object fixes

---

website/docs/advanced-concepts/audit-logs.md

docs: Added information around datasource environments for audit log events

---

website/docs/reference/widgets/chart.mdx

fix: Chart Rehaul diataxis

---

.github/styles/Vocab/technical/accept.txt
website/docs/reference/widgets/json-form.md

fix: JSON Form rehaul

---

website/docs/reference/widgets/form.md

fix: Form Rehaul

---

.github/styles/Google/Headings.yml
.github/styles/Vocab/technical/accept.txt
website/docs/reference/widgets/button/README.md

fix: Rehaul - button widget

---

website/docs/reference/widgets/chart.mdx

fix: Chart Rehaul review-fix

---

website/docs/reference/widgets/form.md

fix: Form review

---

website/docs/reference/widgets/button/README.md
website/docs/reference/widgets/select.md

chore: Select and Button widget fixes

---

.github/styles/Vocab/technical/accept.txt
website/docs/reference/widgets/table/README.md
website/docs/reference/widgets/text.md

fix: Text Rehaul

---

.github/styles/Google/Headings.yml
.github/styles/Vocab/technical/accept.txt
website/docs/reference/widgets/input.md

fix: Input Rehaul

---

.github/styles/Google/Headings.yml
.github/styles/Vocab/technical/accept.txt
website/docs/reference/widgets/button/README.md
website/docs/reference/widgets/checkbox-group.md
website/docs/reference/widgets/checkbox.md
website/docs/reference/widgets/currency-input.md
website/docs/reference/widgets/document-viewer.md
website/docs/reference/widgets/filepicker.md
website/docs/reference/widgets/form.md
website/docs/reference/widgets/icon-button.md
website/docs/reference/widgets/input.md
website/docs/reference/widgets/list.md
website/docs/reference/widgets/multiselect.md
website/docs/reference/widgets/phone-input.md
website/docs/reference/widgets/progress.md
website/docs/reference/widgets/radio-group.md
website/docs/reference/widgets/rich-text-editor.md
website/docs/reference/widgets/select.md
website/docs/reference/widgets/switch-group.md
website/docs/reference/widgets/switch.md
website/docs/reference/widgets/table/README.md
website/docs/reference/widgets/text.md
website/docs/reference/widgets/tree-select.md

I have:
**FIxes**
- Updated methods for rehauled widgets
- Added cross link to Server side filtering in MultiSelect
- minor fixes

chore: Update methods in widgets

---

website/docs/reference/widgets/button/README.md
website/docs/reference/widgets/checkbox-group.md
website/docs/reference/widgets/document-viewer.md
website/docs/reference/widgets/filepicker.md
website/docs/reference/widgets/table/README.md
website/docs/reference/widgets/table/inline-editing.md
website/docs/reference/widgets/text.md

fix: Data type fixes and review updates 

---

website/docs/connect-data/concepts/Datasource-Environments.md
website/docs/connect-data/how-to-guides/setup-datasource-environments.md

fix: callout fix for Datasource Environments

---

.github/workflows/lint.yml
.vale.ini

- Removed vale internal checks.
- Added `mdx` file formats for styleguide checks.
I have:

chore: Updated linter settings

---

.github/styles/Google/Headings.yml
website/docs/connect-data/concepts/Datasource-Environments.md
website/docs/connect-data/how-to-guides/setup-datasource-environments.md

fix: Git + Datasource Environments

---

website/docs/reference/widgets/iframe.md

fix: Iframe update

---

website/docs/reference/widgets/multiselect.md
website/docs/reference/widgets/select.md

feat: Label and Value property for Select and MultiSelect

---

website/docs/core-concepts/writing-code/javascript-editor-beta/asynchronous-javascript-function-settings.md

chore: removed repeated content

---

website/docs/reference/widgets/container.md

fix: Rehaul - Container

---

website/docs/reference/widgets/audio-recorder.md
website/docs/reference/widgets/container.md

chore: update heading for methods in widgets (container, audio recorder)

---

website/docs/reference/widgets/maps.md

fix: Live Location Map

---

website/vercel.json

chore: added redirect urls for 404

---

website/docs/reference/widgets/chart.mdx
website/docs/reference/widgets/map-chart.md

fix: Map Chart

---

website/vercel.json

the redirect rule was failing
I have:

chore: fixed not loading images

---

website/docs/reference/widgets/divider.md

fix: Divider

---

website/docs/reference/widgets/menu/README.md
website/docs/reference/widgets/sliders/category-slider.md

fix: Category Slider

---

.github/styles/Google/Headings.yml
website/docs/reference/widgets/camera.md

fix: Rehaul - Camera

---

website/docs/reference/widgets/code-scanner.md

fix: Rehaul -  Code Scanner

---

website/docs/reference/widgets/sliders/number-slider.md
website/docs/reference/widgets/sliders/range-slider.md

fix: Range Slider

---

website/docs/reference/widgets/audio.md
website/docs/reference/widgets/iframe.md
website/docs/reference/widgets/input.md
website/docs/reference/widgets/multi-tree-select.md
website/docs/reference/widgets/video.md

fix: Events Intro

---

website/docs/connect-data/how-to-guides/README.md
website/docs/connect-data/how-to-guides/connect-datasource.md

fix: typo on datasource

---

website/docs/reference/appsmith-framework/widget-actions/store-value.md

I have:
-----------------------------------
- Updated the definition of `persist` parameter in storeValue()

chore: Update `presist` definition in storeValue()

---

website/docs/connect-data/concepts/README.md

fix: Add Datasource environments to landing page

---

website/docs/getting-started/setup/installation-guides/aws-ecs-on-fargate.md

chore: fixed 404

---

website/docs/build-apps/how-to-guides/Server-side-pagination-in-table.md

fix: Setup Server-side Pagination on Table

---

website/docs/build-apps/how-to-guides/Server-side-pagination-in-table.md

Updates:
added Configure total records section
added prepared statements callout
Removed the cursor API example, for now, will try Graphql and add it next week
Removed one GIF(cursor-one)
I have:

fix: Review fixes for Server-Side Pagination on Table

---

website/docs/getting-started/setup/instance-configuration/authentication/json-web-tokens-jwt.md

feat: Added rawIdToken content

---

website/docs/build-apps/how-to-guides/submit-form-data.md

Updates-
- Removed the table binding example.
- Rephrased a few lines.
I have:

fix: Submit form data - review

---

website/docs/build-apps/how-to-guides/refresh-table-data.md

Update-
- Removed JS code snippet
I have:

fix: Refresh Table Data After Updates - REVIEW FIX

---

website/docs/advanced-concepts/granular-access-control/roles.md

I have:
------------------------------
- Updated `Datasource and queries` to `Datasource and environments`. 
- Added execute permission for queries under the Application Resources.
- Removed queries from Datasource and Environments

chore: Updating roles tables

---

website/sidebars.js

- Moved deployment architecture below best practices on the sidebar.
I have:

chore: updated sidebar

---

website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/README.md
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/README.md
website/docs/getting-started/setup/upgrade-to-business-edition/README.md

SAML and OIDC SSO callout.
fixes: #1711
I have:

chore: update to callouts

---

website/docs/core-concepts/writing-code/javascript-editor-beta/README.md

feat: Adds mutable JS variable video

---

website/package-lock.json
website/package.json

- Docusaurus and Browserslist.
I have:

chore: updated versions

---

website/docs/core-concepts/writing-code/ext-libraries.md

fix: Duplicate content - Custom JS Libraries

---

website/docs/help-and-support/troubleshooting-guide/deployment-errors.mdx

- Added a new troubleshooting guide under:
* Troubleshooting 
* Deployment Errors
Fixes #1721
I have:

feat: add troubleshooting guide for helm upgrade

---

website/package-lock.json
website/package.json
website/src/components/Tags.js
website/src/css/custom.css

chore: Update docusaurus version

---

website/docs/getting-started/setup/installation-guides/kubernetes/README.mdx

chore: fixed typo

---

.github/workflows/deploy.yml

- Update the Algolia index every six hours instead of every merge.
I have:

fix: update the crawler run

---

website/docs/help-and-support/troubleshooting-guide/action-errors/datasource-errors.md

fix: Can't delete datasource error

---

website/docs/getting-started/setup/installation-guides/docker/README.mdx

chore: fixed the local url

---

website/docs/getting-started/setup/installation-guides/google-cloud-run.mdx

chore: fixed tabs for google cloud run

---

website/docs/getting-started/setup/installation-guides/aws-ecs.md

- updated title
- added sub section headings for more readability
I have:

chore: updated AWS ECS on EC2

---

website/docs/connect-data/how-to-guides/README.md
website/docs/connect-data/how-to-guides/how-to-use-the-camera-image-widget-to-upload-download-images.md

Updated [Upload Images to and from S3](https://docs.appsmith.com/connect-data/how-to-guides/how-to-use-the-camera-image-widget-to-upload-download-images) to address the following:
- Change the title from "Upload Images to and from S3" to "Upload Images Using Camera".
- Remove the "Upload image using Image widget" section.
- Make the topic generic and use S3 as an example.
- Improvise the topic to edit and remove outdated video, field names, and other UI-specific information.
- Add prerequisites section.
- Edit the intro and ensure the style guide is followed.
I have:

fix: Upload images using camera to S3

---

website/docs/connect-data/how-to-guides/how-to-use-the-camera-image-widget-to-upload-download-images.md

As discussed, removed the manual data addition part in point 9:
"In Content, add data manually by writing an object with a text and data property, or fetch data from the camera widget. "
I have:

fix: Minor update to upload camera image using S3

---

website/docs/reference/widgets/json-form.md
website/docs/reference/widgets/table/README.md

fix: JSON form one click

---

website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/active-directory.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/auth0.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/okta.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/ping-identity.md

fix: OIDC add offline_access

---

website/docs/connect-data/reference/querying-amazon-s3.md

fix: Mention the permission needed-#121

---

website/docs/getting-started/setup/instance-configuration/authentication/json-web-tokens-jwt.md

fix: userClaims OIDC

---

website/docs/advanced-concepts/user-provisioning-group-sync.mdx

fix: Remove SAML pre-req

---

website/docs/advanced-concepts/user-provisioning-group-sync.mdx

fix: Removed SAML references from SCIM

---

website/docs/getting-started/setup/installation-guides/aws-ecs.md

chore: fix broken sentence

---

website/docs/build-apps/how-to-guides/Setup-Server-side-Pagination-on-List.md
website/docs/build-apps/how-to-guides/Setup-Server-side-Searching-on-Table.md

fix: Review Comments for pagination

---

website/docs/getting-started/setup/installation-guides/aws-ecs-on-fargate.md

feat: One-click AWS ECS on Fargate

---

website/docs/getting-started/setup/installation-guides/azure-aci.md
website/docs/getting-started/setup/instance-management/how-to-get-container-logs.md
website/docs/getting-started/setup/instance-management/update-appsmith.mdx

* Updated structure of doc
* Removed tabs
* Added section for community edition deployment
* Removed update Appsmith section and added to update Appsmith doc
* Removed container logs section and added to container logs Azure container instance section
Fixes - #1772
I have:

feat: one-click Azure Container Instance

---

website/docs/getting-started/setup/installation-guides/README.md
website/docs/getting-started/setup/instance-configuration/README.mdx
website/docs/getting-started/setup/instance-management/README.mdx

chore: fixed titles

---

website/docs/build-apps/how-to-guides/Setup-Server-side-Searching-on-Table.md
website/docs/connect-data/how-to-guides/fetch-and-filter-data-in-sql.md
website/sidebars.js

fix: Fetch and filter data in SQL

---

website/docusaurus.config.js
website/src/css/custom.css
website/src/theme/DocItem/Footer/index.js
website/src/theme/DocSidebar/index.js

fix: remove footer and add copyright to sidebar

---

website/src/css/custom.css
website/src/theme/DocSidebar/index.js

chore: update copyright style

---

website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/active-directory.md

chore: updated sub instead of email

---

website/src/css/custom.css
website/src/theme/DocSidebar/index.js

- removed inline styles.
I have:

chore: updated css

---

website/src/components/feedback/feedback.js
website/src/components/feedback/feedbackComments.js
website/src/components/feedback/feedbackHelper.js
website/src/components/feedback/feedbackMessage.js
website/src/components/feedback/index.js
website/src/css/custom.css

feat: add inline comments to feedback widget

---

website/docs/getting-started/setup/installation-guides/aws-ecs-on-fargate.md

chore: updated command

---

.github/workflows/generate-docs-embeddings.yml

feat: Github action to generate embeddings

---

website/docs/advanced-concepts/version-control-with-git/connecting-to-git-repository.mdx

Added permissions for Connect / Disconnect Git

---

website/docs/learning-and-resources/sample-apps.md

fix:change sample app link

---

website/docs/help-and-support/troubleshooting-guide/action-errors/README.md

fix: 504 Gateway Timeout Errors

---

website/docs/getting-started/setup/installation-guides/docker/README.mdx

chore: remove section

---

.github/workflows/generate-docs-embeddings.yml

chore: updateurl

---

website/docs/advanced-concepts/user-provisioning-group-sync.mdx

chore: add prerequisite

---

.github/workflows/generate-doc-pdf-and-upload.yml

chore: add action for generating a doc pdf and upload

---

website/docs/write-code/reference/Built-in-JS-Libraries.md

chore: removed xml parser

---

website/docs/connect-data/reference/querying-google-sheets.md

fix: Ghseet update code

---

website/docs/getting-started/setup/installation-guides/aws-ami.md
website/docs/getting-started/setup/installation-guides/aws-ecs-on-fargate.md
website/docs/getting-started/setup/installation-guides/aws-ecs.md
website/docs/getting-started/setup/installation-guides/azure-aci.md
website/docs/getting-started/setup/installation-guides/docker/README.mdx
website/docs/getting-started/setup/installation-guides/google-cloud-run.mdx
website/docs/getting-started/setup/installation-guides/kubernetes/README.mdx

for all installation guides
I have:

chore: add section

---

.github/styles/Google/Headings.yml
website/docs/getting-started/setup/installation-guides/air-gapped.md
website/docs/product/telemetry.md
website/sidebars.js

fix: Added guide for air-gapping and fixed telemetry

---

website/docs/build-apps/overview.md
website/docs/connect-data/concepts/connection-pooling.md
website/docs/connect-data/concepts/dynamic-queries.md
website/docs/connect-data/how-to-guides/how-to-pass-params-to-an-api.mdx
website/docs/connect-data/overview.md
website/docs/core-concepts/writing-code/javascript-editor-beta/README.md
website/docs/getting-started/setup/README.md
website/docs/getting-started/tutorials/README.md
website/docs/getting-started/tutorials/start-building.md
website/docs/intro.md
website/docs/product/security.md
website/docs/write-code/concepts/execute-onpageload.md
website/sidebars.js

fix: Feature/clean up

---

website/docs/advanced-concepts/granular-access-control/roles.md
website/docs/connect-data/concepts/Datasource-Environments.md
website/docs/connect-data/how-to-guides/setup-datasource-environments.md

feat: custom environment

---

website/docs/intro.md

fix: Fixed JavaScript case in intro

---

website/docs/advanced-concepts/version-control-with-git/environments-with-git.md
website/docs/advanced-concepts/version-control-with-git/working-with-branches.md

fix: Default branch fixes

---

website/docs/connect-data/reference/open-ai.md

fix: Open AI review changes

---

website/docs/core-concepts/writing-code/ext-libraries.md

chore: Updates the doc with support for ESM libraries

---

website/docs/getting-started/setup/installation-guides/aws-ami.md
website/docs/getting-started/setup/installation-guides/aws-ecs-on-fargate.md
website/docs/getting-started/setup/installation-guides/aws-ecs.md
website/docs/getting-started/setup/installation-guides/azure-aci.md
website/docs/getting-started/setup/installation-guides/docker/README.mdx
website/docs/getting-started/setup/installation-guides/google-cloud-run.mdx

chore: updates to wording in installation guides

---

website/src/components/ask-ai/AISearch.jsx
website/src/components/ask-ai/AISearchButton.jsx
website/src/components/ask-ai/AISearchModal.jsx
website/src/components/ask-ai/css/AISearch.css
website/src/components/custom-search/CustomSearchBar.jsx
website/src/components/custom-search/css/CustomSearch.css

chore: incremental style changes

---

website/src/components/ask-ai/AISearch.jsx
website/src/components/ask-ai/css/AISearch.css

chore: fixed typo and min height

---

website/src/components/ask-ai/AISearch.jsx
website/src/components/ask-ai/css/AISearch.css

chore: fixed style and added message to loading indicator

---

website/docs/build-apps/overview.md
website/docs/connect-data/overview.md
website/docs/getting-started/setup/installation-guides/air-gapped.md
website/docs/help-and-support/troubleshooting-guide/README.md
website/docs/help-and-support/troubleshooting-guide/backup-restore-errors.mdx
website/docs/help-and-support/troubleshooting-guide/deployment-error-guides/k8s-helm3.0.4-upgrade-error.md
website/docs/help-and-support/troubleshooting-guide/deployment-error-guides/mongodb-startup-error-postv5.mdx
website/docs/write-code/overview.md
website/sidebars.js

feat: add troubleshooting guide for appsmithctl

---

website/src/theme/DocItem/Footer/index.js

chore: added the edit page

---

website/src/components/ask-ai/AISearch.jsx

chore: updated terms

---

.github/styles/Vocab/technical/accept.txt
website/docs/getting-started/setup/installation-guides/google-cloud-run/setup-to-integrate-sso.mdx
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/active-directory.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/auth0.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/aws-cognito.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/okta.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/ping-identity.md

chore: Updates to Google Cloud run SSO

---

website/docs/build-apps/how-to-guides/submit-form-data.md
website/sidebars.js

fix: Update data guide

---

website/docs/getting-started/setup/installation-guides/docker/README.mdx

chore: fixed indendation

---

website/docs/getting-started/setup/deployment-architecture.md
website/docs/getting-started/setup/instance-management/supervisor.md

fix: Change NGINX to Caddy

---

website/config.json

chore: updates to the search for custom cards

---

website/docs/build-apps/how-to-guides/display-map-markers.md
website/sidebars.js

fix: Display Map Markers

---

website/sidebars.js
website/src/components/ask-ai/AISearch.jsx
website/src/components/feedback/feedbackHelper.js

- also removed the reuse app entities page
I have:

fix: add event for registering AI search

---

website/docs/build-apps/how-to-guides/display-map-markers.md

fix: Map review fix

---

website/docs/build-apps/how-to-guides/navigate-between-pages.md

fix: Page navigation review comments

---

website/docs/getting-started/setup/installation-guides/aws-ecs/setup-postgresql-aws-ecs.mdx
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/active-directory.mdx
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/auth0.mdx
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/okta.mdx
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/ping-identity.mdx

chore: Updated title and cross-reference term

---

website/docs/getting-started/setup/instance-management/maintenance-window.md

chore: fixed-indentation

---

.github/styles/Vocab/technical/accept.txt
website/docs/getting-started/setup/installation-guides/air-gapped.md

fix: Updated airgapped documentation to make clear the requirements

---

website/docs/build-apps/how-to-guides/update-list-data-inline.md
website/docs/build-apps/how-to-guides/update-list-data.md
website/sidebars.js

fix: Guide to update list data

---

website/docs/core-concepts/writing-code/ext-libraries.md

fix: URL fix for accessing installed lib

---

website/docs/getting-started/setup/instance-configuration/custom-mongodb-redis.md

chore-add-backup-restore-steps
I have:

chore: Add backup and restore steps

---

website/docs/advanced-concepts/version-control-with-git/updating-local-file-path.md

chore: updated callout with persistent storage

---

website/docs/connect-data/how-to-guides/how-to-download-files-using-api.md

fix: Review comment fixes for download files

---

website/docs/build-apps/how-to-guides/display-select-options-dynamically.md
website/sidebars.js

chore: restructured how-to guides

---

website/docs/build-apps/how-to-guides/navigate-between-pages.md

fix: Removed local storage section

---

website/docs/getting-started/setup/best-practices.md

fix: Improved best practices to recommend the correct setup

---

website/docs/core-concepts/writing-code/workflows.md

fix: Update Trigger UI to add Two levels of Success callbacks

---

website/docs/getting-started/setup/instance-configuration/disable-user-signup.md

docs: Update disable-user-signup.md

---

website/docs/getting-started/setup/manage-plans/downgrade-plan.mdx

docs: fix typo in downgrade-plan.mdx

---

website/docs/advanced-concepts/sharing-data-across-pages.md
website/src/components/zoom-image/ZoomableImage.css

* Added styles for image border and box-shadow
* Removed old images from the share data across pages doc.
I have:

chore: Fix style for images

---

website/docs/write-code/best-practices.md
website/sidebars.js

fix:Native and Lodash function best practices

---

website/docs/advanced-concepts/sharing-data-across-pages.md

fix: Revamp share data across pages

---

website/docs/reference/widgets/chart.mdx

fix: Fusion chart callout

---

website/docs/connect-data/concepts/connection-pooling.md

chore: Add business tag

---

website/docs/advanced-concepts/granular-access-control/roles.md

chore: fixed table format

---

website/docs/build-apps/how-to-guides/set-up-websockets.md
website/docs/build-apps/how-to-guides/setup-polling.md

fix: Websockets and polling review changes

---

website/docs/getting-started/setup/instance-management/appsmithctl.mdx

chore: updated to add container directory

---

website/docs/product/telemetry.md

- Add data collected for billing.
I have:

chore: Update Telemetry

---

website/docs/product/telemetry.md

chore: fix typo

---

website/vercel.json

fix: Broken link fixes

---

website/docs/getting-started/setup/installation-guides/docker/README.mdx

chore: fix docker instructions

---

website/docs/connect-data/reference/querying-google-sheets.md

chore: fix Google sheets reference

---

website/docs/build-apps/how-to-guides/add-remove-inputs-in-list.md
website/sidebars.js

fix: Guide to create dynamic inputs in List

---

website/docs/getting-started/setup/environment-variables.md

fix: Update environment-variables.md

---

website/docs/getting-started/setup/instance-configuration/custom-domain/custom-ca-root-certificate.md

chore: fixed code block

---

website/docs/build-apps/how-to-guides/Create-Custom-Widgets-Using-Iframe.md
website/docs/build-apps/how-to-guides/custom-widget-using-vanillajs.md
website/docs/reference/widgets/custom.md

fix: Callout custom widget

---

website/docs/product/security.md

Based on conversation at https://theappsmith.slack.com/archives/CGBPVEJ5C/p1705900884231779?thread_ts=1705559979.178149&cid=CGBPVEJ5C.
* https://github.com/appsmithorg/appsmith-ee/issues/234
- 

docs: Add notes about rate limiting

---

website/docs/learning-and-resources/sample-apps.md

- added sample apps for custom widget
* 
- 

fix: custom sample apps

---

website/src/components/ask-ai/AISearch.jsx
website/src/components/custom-search/CustomSearchBar.jsx

- Fixed path to images and CSS
* 
- 

chore: Fix search image issue

---

website/docs/connect-data/reference/README.md
website/docs/connect-data/reference/querying-amazon-s3.md
website/docs/connect-data/reference/querying-google-sheets.md
website/docs/connect-data/reference/querying-postgres.md
website/docs/connect-data/reference/using-smtp.md
website/docs/reference/appsmith-framework/query-object.mdx
website/docs/reference/appsmith-framework/widget-actions/download.md
website/docs/reference/appsmith-framework/widget-actions/intervals-time-events.md
website/docs/reference/appsmith-framework/widget-actions/navigate-to.md
website/docs/reference/widgets/button-group/README.md
website/docs/reference/widgets/chart.mdx
website/docs/reference/widgets/filepicker.md
website/docs/reference/widgets/form.md
website/docs/reference/widgets/icon-button.md
website/docs/reference/widgets/iframe.md
website/docs/reference/widgets/list.md
website/docs/reference/widgets/maps.md
website/docs/reference/widgets/modal.md
website/docs/reference/widgets/select.md
website/docs/reference/widgets/table/README.md
website/docs/reference/widgets/tabs.md

closes #2067 
Added cross references for corresponding How-to guides in the Reference docs.
* 
- 

fix:Link guides in References

---

website/docs/build-apps/how-to-guides/Create-Custom-Widgets-Using-Iframe.md
website/docs/build-apps/how-to-guides/custom-widget-using-vanillajs.md
website/docs/reference/widgets/custom.md

fix: Custom widget callout

---

website/docs/connect-data/reference/querying-firestore.md

fix: pagination example Firestore

---

website/docs/reference/widgets/video.md

fix: Video Widget URL Property Changes

---

website/docs/learning-and-resources/sample-apps.md

Updated the links to the correct sample apps.
* 
- 

fix: updated broken sample app links

---

website/docs/reference/widgets/custom.md

documents the custom widget auto height property
* https://github.com/appsmithorg/appsmith/issues/30900
- 

feat: Custom widget auto height

---

website/docs/connect-data/reference/querying-amazon-s3.md
website/docs/connect-data/reference/querying-arango-db.md
website/docs/connect-data/reference/querying-dynamodb.md
website/docs/connect-data/reference/querying-elasticsearch.md
website/docs/connect-data/reference/querying-mongodb/README.md
website/docs/connect-data/reference/querying-mssql.md
website/docs/connect-data/reference/querying-mysql.md
website/docs/connect-data/reference/querying-oracle.md
website/docs/connect-data/reference/querying-postgres.md
website/docs/connect-data/reference/querying-redis.md
website/docs/connect-data/reference/querying-redshift.md
website/docs/connect-data/reference/querying-snowflake-db.md

fix: Datasource whitelist callouts

---

website/docs/build-apps/how-to-guides/Create-Custom-Widgets-Using-Iframe.md
website/sidebars.js

fix: Custom widget guide video

---

website/sidebars.js

- Moved the send message to embedded Appsmith guide under Embed Appsmith
* 
- 

chore: Moved message guide under Embed Appsmith

---

website/docs/advanced-concepts/embed-appsmith-into-existing-application.mdx

- Added Footnote for GitHub SSO limitation
* 
- 

chore: added limitation as a footnote.

---

website/docs/getting-started/setup/installation-guides/aws-ecs-on-fargate.md

- Formatting issue with code block
* 
- 

chore: fixed formatting.

---

.github/ISSUE_TEMPLATE/--add-documentation-request.yaml
.github/ISSUE_TEMPLATE/--documentation-improvement.yaml

- Updates to issue templates
* 
- 

chore: updates to template

---

website/docs/getting-started/setup/deployment-architecture.md

- Removed deployment architecture image.
* 
- 

chore: removed image

---

.github/styles/config/vocabularies/technical/accept.txt
website/docs/connect-data/reference/databricks.md

fix: UserAgent databricks

---

website/docs/advanced-concepts/custom-authentication.md

fix: Refresh access token code fix

---

website/docs/reference/widgets/json-form.md

fix: JSON Form submit button

---

website/docs/reference/widgets/multiselect.md
website/docs/reference/widgets/select.md

fix: Multi-select mapping example 

---

website/docs/connect-data/reference/querying-firestore.md
website/docs/reference/widgets/filepicker.md

fix: Filepicker data format

---

website/docs/build-apps/how-to-guides/create-custom-charts.md

fix: Create Custom Charts using ECharts

---

website/docs/reference/widgets/map-chart.md

feat: E-chart MapChart widget

---

website/docs/core-concepts/writing-code/workflows.md

fix:  Trigger UI Actions

---

website/docs/packages/tutorial/js-module.md
website/docs/packages/tutorial/query-module.md

fix: Modules user testing fixes

---

website/docs/connect-data/reference/databricks.md

fix: UserAgent Tag Databricks

---

website/docs/reference/widgets/rich-text-editor.md

fix: RTE  onTextChanged

---

website/docs/packages/tutorial/query-module.md

fix: Module Next steps

---

website/docs/workflows/how-to-guides/README.md
website/docs/workflows/how-to-guides/create-approval-workflow.md
website/docs/workflows/how-to-guides/set-up-automatic-processing.md
website/docs/workflows/how-to-guides/trigger-workflow-from-appsmith-app.md
website/docs/workflows/tutorials/create-workflow.md
website/sidebars.js

fix: updates based on usability tests

---

website/docs/workflows/tutorials/create-workflow.md

- Updates to the tutorial for modifying the flow to use a blank API.
* 
- Usability test fixes

fix: Updates to the tutorial.

---

website/docs/workflows/README.md
website/docs/workflows/reference/workflow-functions.md
website/docs/workflows/reference/workflow-queries.md
website/docs/workflows/tutorials/create-workflow.md

- Cross-links
- Update link headings
- Add properties to show level 4 headings
* 
- 

fix: workflow feedback

---

website/docs/advanced-concepts/more/backup-restore.md

This section is outdated information and is misleading. This PR removes it.

chore: Removed outdated information on backup/restore

---

website/docs/packages/how-to-guides/use-query-inside-js-module.md

- JS module guide 
- How to use queries inside JS module
* 
- 

fix: Login Use case - JS module

---

website/docs/packages/how-to-guides/use-query-inside-js-module.md

fix: LoginModule Guide

---

website/docs/getting-started/setup/instance-management/appsmithctl.mdx

- Removed the option for unencrypted backup archive
* 
- 

chore: remove unencrypted option

---

website/docs/workflows/README.md
website/docs/workflows/how-to-guides/trigger-workflow-from-appsmith-app.md

fix: Simplified the docs around trigger using workflow query

---

website/docs/build-apps/how-to-guides/send-messages-between-your-app-and-appsmith.md
website/docs/connect-data/how-to-guides/fetch-and-filter-data-in-sql.md
website/docs/reference/appsmith-framework/widget-actions/README.md
website/vercel.json

chore: fixed redirects on docs

---

website/docs/build-apps/how-to-guides/Create-Custom-Widgets-Using-Iframe.md
website/docs/build-apps/how-to-guides/custom-widget-using-vanillajs.md

fix: Pass parameters to custom widget

---

website/docs/connect-data/reference/graphql.md

fix: GraphQL Fetch records code fix

---

website/docs/workflows/README.md
website/docs/workflows/how-to-guides/create-approval-workflow.md
website/docs/workflows/how-to-guides/set-up-automatic-processing.md
website/docs/workflows/how-to-guides/trigger-workflow-from-appsmith-app.md
website/docs/workflows/reference/workflow-functions.md
website/docs/workflows/tutorials/create-workflow.md

fix: workflow improvements

---

website/docs/advanced-concepts/embed-appsmith-into-existing-application.mdx
website/docs/build-apps/how-to-guides/send-messages-between-your-app-and-appsmith.md

chore: updates to reflect private embed as an Enterprise only feature

---

website/docs/reference/widgets/select.md

- Fixed in the code block for `setSelectedOption`
* 
- NA

chore: fixed typo 

---

website/docs/connect-data/reference/querying-google-sheets.md

fix: Update Google Sheets datasource reference for restricted access

---

.github/styles/config/vocabularies/technical/accept.txt
website/docs/getting-started/setup/instance-configuration/custom-mongodb-redis.md

- Add info about serverless MongoDB Atlas not supporting replica set
* 
- NA

chore: fix prerequisites -External MongoDB

---

website/docs/advanced-concepts/embed-appsmith-into-existing-application.mdx

-  Removed Google SSO from Embed Appsmith section for Private Embeds
* 
- 

chore: removed Google SSO

---

website/docs/build-apps/how-to-guides/Create-Custom-Widgets-Using-Iframe.md
website/docs/reference/widgets/custom.md

fix: Custom widget

---

website/docs/help-and-support/troubleshooting-guide/gac-errors.mdx

chore: fix troubleshooting scenarios

---

website/docs/help-and-support/troubleshooting-guide/gac-errors.mdx

chore: minor updates

---

website/docs/workflows/tutorials/create-workflow.md

chore: minor fix to show Deploy button instead of Publish

---

website/docs/reference/widgets/table/README.md

fix: setSelectedRowIndices

---

website/docs/reference/widgets/table/column-settings.md
website/docs/reference/widgets/table/inline-editing.md

fix: Editable example

---

website/sidebars.js

- Changed placement of Manage Apps and Users in sidebar
* 
- NA

chore: reordered side bar

---

website/docs/help-and-support/troubleshooting-guide/deployment-errors.mdx

fix: Issue with Disk Space

---

website/docs/advanced-concepts/user-provisioning-group-sync.mdx

fix: scim full form

---

website/docs/workflows/tutorials/create-workflow.md

- Updated Workflow API URL
* 
- 

chore: updated workflow tutorial API URL

---

website/docs/getting-started/setup/installation-guides/aws-ami.md
website/docs/getting-started/setup/installation-guides/aws-ecs-on-fargate.md
website/docs/getting-started/setup/installation-guides/aws-ecs/aws-ecs-on-ec2.md

- Updated AWS AMI, AWS ECS on EC2, and AWS ECS on Fargate to add outbound rule
* 
- #2191 

chore: updates for adding outbound rule

---

website/docs/getting-started/setup/instance-configuration/custom-mongodb-redis.md

- Removed stateless information as it was misleading
* 
- 

chore: removed stateless information as it was misleading

---

website/docs/getting-started/setup/instance-configuration/email/microsoft-365.md
website/sidebars.js

feat: Microsoft 365

---

website/docs/getting-started/setup/installation-guides/docker/README.mdx

- Added a version to the docker-compose.yml file.
* 
- 

chore: Added version

---

website/docs/getting-started/setup/installation-guides/digitalocean.md

- removed irrelevant information about the digital ocean offer
* 
- 

chore: removed irrelevant information about digital ocean offer

---

website/docs/getting-started/setup/environment-variables.md

chore: fix env variable name

---

website/docs/workflows/reference/workflow-functions.md

- Added async to the signature of the method and also in the description
* 
- 

chore: added info on async nature of assignRequest

---

website/docs/getting-started/setup/installation-guides/aws-ecs-on-fargate.md

- Revising to provide recent intended links
* 
- 

docs(aws-ecs-on-fargate): key pair section links

---

website/docs/reference/widgets/custom.md

fix: triggerEvent custom

---

website/docs/getting-started/setup/installation-guides/aws-ecs/aws-ecs-on-ec2.md

- 
- [x ] Documentation Overhaul
* 
- [x ] Error in documentation
https://github.com/appsmithorg/appsmith-docs/issues/2464
- [ x] Validated the modifications made to the content on the deploy preview.

chore: add port mappings configuration for ecs on ec2 doc

---

website/docs/build-apps/how-to-guides/export-audit-logs.md
website/docs/build-apps/how-to-guides/how-to-export-audit-logs.md
website/docs/build-apps/how-to-guides/usage-app.md
website/sidebars.js

feat: How to export audit logs

---

.github/workflows/generate-pdf-for-ai.yaml

- Added a GitHub action for generating docs pdf and upload to AI
* 
- 

feat: generate pdf for ai

---

.github/workflows/generate-pdf-for-ai.yaml

chore: Updated install command

---

.github/workflows/generate-pdf-for-ai.yaml

chore: updates to the upload workflow

---

.github/styles/config/vocabularies/technical/accept.txt
website/docs/reference/widgets/custom.md

fix: onModelChange example

---

website/docs/connect-data/how-to-guides/setup-datasource-environments.md

fix: Switch environments

---

website/docs/reference/widgets/document-viewer.md

fix: Document Viewer pdf size

---

LICENSE

- Added License (Apache License 2.0)
* 
- 

fix: Add License

---

website/docs/help-and-support/troubleshooting-guide/deployment-errors.mdx

fix: Appsmith Unable to Connect to Azure PostgreSQL Database

---

website/docs/product/support.md

- Fix invite link on Support Doc.
* 
- 

chore: fix the invite link on Support doc

---

website/docusaurus.config.js
website/static/scripts/reotracking.js

chore: add reo tracking

---

website/docs/advanced-concepts/user-provisioning-group-sync.mdx
website/docs/getting-started/setup/instance-configuration/authentication/google-login.md

fix: callout SCIM

---

website/package-lock.json
website/package.json

chore: reinstall reo

---

website/static/scripts/reotracking.js

fix: reo code

---

website/docs/getting-started/setup/environment-variables.md
website/docs/getting-started/setup/instance-configuration/custom-mongodb-redis.md

fix: MongoDB URI special characters

---

website/docs/connect-data/reference/querying-firestore.md

fix: Firestore update

---

.github/styles/config/vocabularies/technical/accept.txt
website/docs/workflows/README.md
website/docs/workflows/how-to-guides/trigger-workflow-from-appsmith-app.md
website/docs/workflows/reference/workflow-triggers.md
website/sidebars.js

- Added a new reference doc for Workflow Triggers
- Removed the coming soon tag for cron
- added cross-references
* 
- 

feat: Scheduled Trigger for Workflows

---

website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/auth0.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/aws-cognito.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/okta.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/ping-identity.md

fix: Okta OIDC Format

---

website/docs/getting-started/setup/instance-configuration/authentication/github-login.md
website/docs/getting-started/setup/instance-configuration/authentication/google-login.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/auth0.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/aws-cognito.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/entra-id.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/okta.md
website/docs/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/ping-identity.md
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/auth0.mdx
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/entra-id.mdx
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/okta.mdx
website/docs/getting-started/setup/instance-configuration/authentication/security-assertion-markup-language-saml/ping-identity.mdx

fix: SAML SSO setup fails on kubernetes HA setup

---

website/docs/write-code/reference/transform-data.md
website/sidebars.js

fix: Transform data

---

website/docs/product/security.md

- Updated Security Doc to add domain whitelisting information
* 
- 

fix: Add domain whitelisting

---

website/src/components/custom-search/CustomSearchBar.jsx
website/src/components/feedback/feedbackHelper.js

- Added analytics to track 'Ask ai' and 'Search' button clicks on the documentation
* 
- #2570 

feat: add Analytics

---

website/docs/getting-started/setup/instance-management/maintenance-window.md

- Fixed indentation for Docker auto-update
* 
- 

chore: fixed indentation

---

website/docusaurus.config.js
website/src/css/custom.css
website/static/scripts/reotracking.js

Reverts appsmithorg/appsmith-docs#2561

fix: Revert "chore: removed reo"

---

website/docs/workflows/reference/workflow-functions.md

chore: fix function call in example.

---

website/docs/getting-started/setup/instance-configuration/custom-domain/custom-ca-root-certificate.md

fix: Custom CA Root - add Values.yaml steps

---

.github/styles/config/vocabularies/technical/accept.txt
website/docs/product/security.md
website/sidebars.js

- Add the link to the privacy policy
- Security doc updates for Appsmith AI
* 
- #2682 

feat: Add privacy policy and security

---

website/docs/advanced-concepts/version-control-with-git/reference/git-settings.md

fix: Updated branch protection defaults

---

website/docs/build-apps/how-to-guides/Create-Custom-Widgets-Using-Iframe.md
website/docs/build-apps/how-to-guides/custom-widget-using-vanillajs.md
website/sidebars.js

fix: Create Image Gallery Using Custom Widget

---

website/src/components/custom-search/CustomSearchBar.jsx

feat: hide Ask AI from docs.

---

website/docs/getting-started/tutorials/the-basics/work-with-data-in-ui.md

chore: fixed query

---

website/docs/build-apps/how-to-guides/README.md
website/docs/connect-data/reference/README.md
website/docs/connect-data/reference/overview.md
website/docs/reference/appsmith-framework/widget-actions/README.md
website/docs/write-code/reference/README.md

fix: landing page

---

website/docs/getting-started/setup/installation-guides/kubernetes/setup-kubernetes-cluster-aws-eks.md

- Updated commands to add placeholders 
* 
- 

chore: fix spacing and parameter names

---

website/src/components/custom-search/CustomSearchBar.jsx

chore: bring back ask ai on docs

---

website/docs/getting-started/setup/installation-guides/kubernetes/README.mdx
website/docs/getting-started/setup/installation-guides/kubernetes/setup-kubernetes-cluster-aws-eks.md
website/docs/getting-started/setup/installation-guides/kubernetes/setup-kubernetes-cluster-aws-eks.mdx

fix: aws-eks cluster setup

---

website/docs/advanced-concepts/_category_.json
website/docs/advanced-concepts/more/_category_.json
website/docs/core-concepts/_category_.json
website/docs/getting-started/_category_.json
website/docs/help-and-support/_category_.json
website/docs/learning-and-resources/_category_.json
website/docs/product/_category_.json
website/docs/reference/_category_.json
website/vercel.json

- removed category json which was listing the folders
- added category redirect rules to fix 404 if someone uses category urls directly.
* 
- 

chore: fixed folder listing

---

website/docs/getting-started/setup/environment-variables.md

fix: APPSMITH_DISABLE_TELEMETRY

---

website/docs/build-apps/how-to-guides/README.md
website/docs/connect-data/reference/overview.md

fix: Broken Links Build Apps

---

website/docs/connect-data/how-to-guides/setup-datasource-environments.md

fix: Switching in View Mode

---

website/docs/packages/overview.md
website/sidebars.js

fix: Sidebar package fix

---

website/docs/getting-started/setup/installation-guides/ansible.md
website/docs/getting-started/setup/installation-guides/aws-ami.md
website/docs/getting-started/setup/installation-guides/aws-ecs-on-fargate.md
website/docs/getting-started/setup/installation-guides/aws-ecs/aws-ecs-on-ec2.md
website/docs/getting-started/setup/installation-guides/azure-aci.md
website/docs/getting-started/setup/installation-guides/digitalocean.md
website/docs/getting-started/setup/installation-guides/docker/README.mdx
website/docs/getting-started/setup/installation-guides/google-cloud-run.mdx
website/docs/getting-started/setup/installation-guides/kubernetes/README.mdx

fix: Whitelist Callout

---

website/docs/reference/widgets/table/README.md

fix: SheetJS

---

.github/styles/config/vocabularies/technical/accept.txt
website/docs/advanced-concepts/granular-access-control/reference/default-roles.md
website/docs/advanced-concepts/granular-access-control/roles.md
website/docs/getting-started/setup/instance-configuration/admin-settings.mdx
website/docs/reference/appsmith-framework/context-object.md

fix: Organization Administrator role

---

website/docs/getting-started/tutorials/build-your-first-app.md
website/docs/getting-started/tutorials/the-basics/work-with-data-in-ui.md
website/sidebars.js
website/vercel.json

fix: Build Your First App

---

website/docs/getting-started/setup/instance-management/api-reference.md
website/docs/getting-started/setup/instance-management/supervisor.mdx
website/sidebars.js

fix: Monitor installations

---

website/vercel.json

fix: Tutorials redirects

---

website/docs/getting-started/setup/instance-management/api-reference.md

fix: Endpoint URL

---

website/docs/workflows/how-to-guides/create-approval-workflow.md

fix: Create approval workflow

---

website/docs/help-and-support/troubleshooting-guide/action-errors/datasource-errors.md

fix: Malformed request error

---

website/sidebars.js

fix: Beta tag

---

website/docs/sample-workflow-tests/sample_config.json

FIX: Create sample_config.json

---

website/docs/advanced-concepts/user-provisioning-group-sync.mdx

fix: SCIM v2.0

---

website/docs/getting-started/setup/manage-plans/downgrade-plan.mdx

fix: Cancel Subscription

---

website/docs/packages/reference/versioning.md

fix: Arcade Managing Package Versions

---

website/src/components/ask-ai/AISearchButton.jsx
website/src/components/ask-ai/AISearchModal.jsx
website/src/components/ask-ai/css/AISearch.css

feat: Ask AI using Agents

---

scripts/file_hashes.json
scripts/processed_files.txt
website/docs/connect-data/reference/gmail.json.md
website/docs/connect-data/reference/mytesttool.md
website/docs/connect-data/reference/testone.md

✅ Automated PR: Generated/updated integration documentation based on changes in the source repository.
**Target Branch:** `docs-staging`
**Source Repo:** [harshilp24/integration-resources-test](https://github.com/harshilp24/integration-resources-test/tree/main/Generic%20UQI%20Creation/uqi_configs)
This PR includes:
- Updated markdown files in `website/docs/connect-data/reference/`
- Updated tracking files in `scripts/` to reflect the processed state for this branch.

docs: update integration docs for docs-staging

---

website/docs/connect-data/how-to-guides/fetch-and-filter-data-in-sql.md

- Fixed some of the small grammatical errors in the doc.
* 
- 

fix: small grammatical changes in documentation

---

website/docs/getting-started/setup/instance-configuration/README.mdx
website/docs/getting-started/setup/instance-configuration/custom-mongodb-redis.md
website/docs/getting-started/setup/instance-configuration/external-postgresql-rds.mdx
website/docs/getting-started/setup/instance-configuration/external-redis.mdx
website/sidebars.js

Added a guide for setting up PostgreSQL on RDS for Keycloak and Temporal. Made wording on a couple of other pages consistent with it. 
* 
- 

feat: add guide for setting up PostgreSQL on RDS

---

website/src/components/custom-search/CustomSearchBar.jsx

fix: ask-ai-click-test

---

website/docs/getting-started/setup/instance-management/update-appsmith.mdx

- Fix a couple of minor whitespace issues
* 
- 

fix: whitespace issue on k8s upgrade

---

website/docs/product/support.md

- Update support page with an additional channel to raise tickets, required information to raise a ticket and a ticket template
* 
- 

feat(support): add support portal as an option to raise tickets

---

website/docs/getting-started/setup/README.md

Update minimum memory to 8 GB instead of 4 B
- 
* 
- 

chore: update minimum recommended install
